LOCATION := http://dl.fedoraproject.org/pub/epel/6/SRPMS/erlang-R14B-04.3.el6.src.rpm
INSTALL_PKGS = erlang-os_mon erlang-sasl erlang-mnesia erlang-erts erlang-kernel erlang-stdlib erlang-compiler erlang-hipe erlang-crypto erlang-xmerl erlang-runtime_tools erlang-public_key erlang-ssl erlang-inets
REQUIREMENT :=

include ../include/Makefile.rpm
