LOCATION := http://dl.fedoraproject.org/pub/epel/6/SRPMS/erlang-R14B-04.1.el6.src.rpm
INSTALL_PKGS = erlang-os_mon erlang-sasl erlang-mnesia erlang-erts erlang-kernel erlang-stdlib erlang-compiler erlang-hipe erlang-crypto

include ../include/Makefile.rpm
