#!/usr/bin/env python

import os
import subprocess


def run_cmd(cmd):
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    return p.stdout.read()


def create_database(name):
    run_cmd(["influx", "-execute", "CREATE DATABASE {}".format(name)])


def print_db_created_result(r):
    print("Created database '{}'".format(r))


iml_db = os.getenv("INFLUXDB_IML_DB")
stratagem_scan_db = os.getenv("INFLUXDB_STRATAGEM_SCAN_DB")

r1 = create_database(iml_db)
print_db_created_result(r1)

r2 = create_database(stratagem_scan_db)
print_db_created_result(r2)
