#!/usr/bin/expect
set user [lindex $argv 0]
set email [lindex $argv 1]
set pass [lindex $argv 2]
set ntp [lindex $argv 3]
spawn ./install
expect {
    "(press RETURN)" {
        send "\r"
        exp_continue
    }
    "EULA.txt" {
        send " "
    }
}
expect {
    "\n:" {
        send " "
        exp_continue
    }
    "(END)" {
        send " "
        exp_continue
    }
    "(yes/no) " {
        send "yes\n"
    }
}
set timeout 300
expect "superuser: "
send $user\n
expect "Email: "
send $email\n
expect "Password: "
send $pass\n
expect "password: "
send $pass\n
expect "\\\[localhost\\\]: "
send $ntp\n
expect "software installation completed successfully"
catch wait reason
set rc [lindex $reason 3]
puts "installation complete: $rc"
exit $rc
