# Generated by rust2rpm

%global crate iml-warp-drive

Name:           rust-%{crate}
Version:        0.1.0
Release:        1%{?dist}
Summary:        streaming IML messages with Server-Sent Events

License:        MIT

URL:            https://crates.io/crates/%{crate}
Source0:        %{crate}-%{version}.crate
Source1:        Cargo.lock
%cargo_bundle_crates -l 1

ExclusiveArch:  x86_64

BuildRequires:  rust
BuildRequires:  cargo

%description
%{summary}.

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install
mkdir -p %{buildroot}%{_unitdir}
cp %{crate}.service %{buildroot}%{_unitdir}

%post
systemctl preset %{crate}.service

%preun
%systemd_preun %{crate}.service

%postun
%systemd_postun_with_restart %{crate}.service

%files
%{_bindir}/%{crate}
%doc %{_cargometadir}/%{name}.json
%attr(0644,root,root)%{_unitdir}/%{crate}.service


%changelog
* Fri Jan 18 2019 Joe Grund <jgrund@whamcloud.com> - 0.1.0-1
- Initial package