#!/bin/sh -e

usage() {

    echo "Usage: $0 {zfs|ldiskfs}"
    exit 1
}

ldiskfs_installer() {
    # create an installer for the user
    cat <<"EOF" > install
#!/bin/sh -e

yum -y install --exclude kmod-lustre-osd-zfs lustre

echo "You need to reboot to activate the Lustre kernel"
EOF

}

zfs_installer() {
    # create an installer for the user
    cat <<EOF > install
#!/bin/sh -e

yum -y install lustre-dkms lustre zfs kernel-devel-[0-9]\*_lustre
EOF

}

case $1 in
    zfs|ldiskfs)
        BACKING_STORE="$1"
    ;;
    *) usage
    ;;
esac

for DISTRO in el6 el7; do
    if [ ! -d $DISTRO ]; then
        continue
    fi
    rm -rf lustre-$BACKING_STORE
    mkdir -p lustre-$BACKING_STORE

    # arrange for cleanup of the dir on exit for any reason
    trap "rm -rf lustre-$BACKING_STORE" EXIT

    cd lustre-$BACKING_STORE

    ${1}_installer

    chmod 755 install
    cd ..

    tar czf lustre-$BACKING_STORE-$DISTRO-installer.tar.gz lustre-$BACKING_STORE
done
