/* automatically generated by rust-bindgen */

pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lu_fid {
    pub f_seq: __u64,
    pub f_oid: __u32,
    pub f_ver: __u32,
}
#[test]
fn bindgen_test_layout_lu_fid() {
    assert_eq!(
        ::std::mem::size_of::<lu_fid>(),
        16usize,
        concat!("Size of: ", stringify!(lu_fid))
    );
    assert_eq!(
        ::std::mem::align_of::<lu_fid>(),
        8usize,
        concat!("Alignment of ", stringify!(lu_fid))
    );
}
pub type lustre_fid = lu_fid;
extern "C" {
    pub fn llapi_fid2path(
        device: *const ::std::os::raw::c_char,
        fidstr: *const ::std::os::raw::c_char,
        path: *mut ::std::os::raw::c_char,
        pathlen: ::std::os::raw::c_int,
        recno: *mut ::std::os::raw::c_longlong,
        linkno: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn llapi_path2fid(
        path: *const ::std::os::raw::c_char,
        fid: *mut lustre_fid,
    ) -> ::std::os::raw::c_int;
}
