#!/bin/bash

if [ $# -gt 0 ]
    then
        export CONFIG_FILE="$1"
    else
        export CONFIG_FILE=tests/integration/shared_storage_configuration/sample_cluster_cfg.json
fi

nosetests --verbosity=2 tests/integration/shared_storage_configuration/test_cluster_setup.py --tc-format=json --tc-file=$CONFIG_FILE

# If the cluster isn't set up properly, just exit and don't execute the tests.
cluster_setup_status=$?
if [ $cluster_setup_status -ne 0 ]; then
    exit $cluster_status_setup
fi

echo "Running tests with config file $CONFIG_FILE"
nosetests --verbosity=2 tests/integration/shared_storage_configuration/ --exclude=".*test_cluster_setup.*" --tc-format=json --tc-file="$CONFIG_FILE"
