.TH chroma-config 1 "Integrated Manager for Lustre" chroma-config

.SH NAME

chroma-config - service configuration command line tool.

.SH SYNOPSIS

.BR chroma-config
.I [setup] | [validate] | [start] | [restart] | [stop]

.BR chroma-config
.I -h | --help

.BR chroma-config
.I -v

.SH DESCRIPTION

This document describes the chroma-config command line tool for Integrated Manager for Lustre.
This tool is to be used to setup, validate, start or stop the Integrated Manager for Lustre services.

.SH OPTIONS

.BR 'setup'
     - Setup the name, email, address and password for
     the first Integrated Manager for Lustre software superuser.

     Optionally you can use the NTP server (Internal or External) used for your site by adding
     the fully qualified domain name when prompted.If no NTP server is set then the Intel
     Manager for Lustre Server's local clock will act as the time source for the entire storage
     cluster.

.BR 'validate'
     - Check all services and print out any errors found
     during the service validation.

.BR 'start'
     - Start the services.

.BR 'stop'
     - Stop the services.

.BR 'restart'
     - Restart the services.

.BR -h
.BR --help
    Print a help message.

.BR -v
     Verbose.
