use iml_wire_types::warp_drive::Cache;

pub(crate) fn get_cache() -> Cache {
    let data = r#"
    {
  "content_type": {},
  "pacemaker_configuration": {},
  "corosync_configuration": {},
  "group": {},
  "user": {},
  "user_group": {},
  "sfa_disk_drive": {},
  "sfa_enclosure": {},
  "sfa_storage_system": {},
  "sfa_job": {},
  "sfa_power_supply": {},
  "sfa_controller": {},
  "snapshot": {},
  "snapshot_interval": {},
  "snapshot_retention": {},
  "target_record": {},
  "snapshot_policy": {},
  "active_alert": {
    "577": {
      "_message": "Updates are ready for server oss1.local",
      "active": true,
      "affected": [
        "/api/host/3/"
      ],
      "alert_item": "/api/host/3/",
      "alert_item_id": 3,
      "alert_item_str": "oss1.local",
      "alert_type": "UpdatesAvailableAlert",
      "begin": "2019-12-15T00:00:08.733612+00:00",
      "dismissed": false,
      "end": null,
      "id": 577,
      "lustre_pid": null,
      "message": "Updates are ready for server oss1.local",
      "record_type": "UpdatesAvailableAlert",
      "resource_uri": "/api/alert/577/",
      "severity": "INFO",
      "variant": "{}"
    },
    "578": {
      "_message": "Updates are ready for server mds2.local",
      "active": true,
      "affected": [
        "/api/host/2/"
      ],
      "alert_item": "/api/host/2/",
      "alert_item_id": 2,
      "alert_item_str": "mds2.local",
      "alert_type": "UpdatesAvailableAlert",
      "begin": "2019-12-15T00:00:08.878686+00:00",
      "dismissed": false,
      "end": null,
      "id": 578,
      "lustre_pid": null,
      "message": "Updates are ready for server mds2.local",
      "record_type": "UpdatesAvailableAlert",
      "resource_uri": "/api/alert/578/",
      "severity": "INFO",
      "variant": "{}"
    },
    "579": {
      "_message": "Updates are ready for server mds1.local",
      "active": true,
      "affected": [
        "/api/host/1/"
      ],
      "alert_item": "/api/host/1/",
      "alert_item_id": 1,
      "alert_item_str": "mds1.local",
      "alert_type": "UpdatesAvailableAlert",
      "begin": "2019-12-15T00:00:09.121633+00:00",
      "dismissed": false,
      "end": null,
      "id": 579,
      "lustre_pid": null,
      "message": "Updates are ready for server mds1.local",
      "record_type": "UpdatesAvailableAlert",
      "resource_uri": "/api/alert/579/",
      "severity": "INFO",
      "variant": "{}"
    },
    "580": {
      "_message": "Updates are ready for server oss2.local",
      "active": true,
      "affected": [
        "/api/host/4/"
      ],
      "alert_item": "/api/host/4/",
      "alert_item_id": 4,
      "alert_item_str": "oss2.local",
      "alert_type": "UpdatesAvailableAlert",
      "begin": "2019-12-15T00:00:09.623579+00:00",
      "dismissed": false,
      "end": null,
      "id": 580,
      "lustre_pid": null,
      "message": "Updates are ready for server oss2.local",
      "record_type": "UpdatesAvailableAlert",
      "resource_uri": "/api/alert/580/",
      "severity": "INFO",
      "variant": "{}"
    },
    "749": {
      "_message": "Target fs-OST0003 offline",
      "active": true,
      "affected": [
        "/api/filesystem/1/",
        "/api/target/6/"
      ],
      "alert_item": "/api/target/6/",
      "alert_item_id": 6,
      "alert_item_str": "fs-OST0003",
      "alert_type": "TargetOfflineAlert",
      "begin": "2020-01-03T18:21:26.484891+00:00",
      "dismissed": false,
      "end": null,
      "id": 749,
      "lustre_pid": null,
      "message": "Target fs-OST0003 offline",
      "record_type": "TargetOfflineAlert",
      "resource_uri": "/api/alert/749/",
      "severity": "WARNING",
      "variant": "{}"
    }
  },
  "filesystem": {
    "1": {
      "bytes_free": 59888226304,
      "bytes_total": 60584181760,
      "cdt_mdt": "/api/target/2/",
      "cdt_status": null,
      "client_count": 0,
      "conf_params": {
        "llite.max_cached_mb": null,
        "llite.max_read_ahead_mb": null,
        "llite.max_read_ahead_whole_mb": null,
        "llite.statahead_max": null,
        "sys.at_early_margin": null,
        "sys.at_extra": null,
        "sys.at_history": null,
        "sys.at_max": null,
        "sys.at_min": null,
        "sys.ldlm_timeout": null,
        "sys.timeout": null
      },
      "content_type_id": 24,
      "files_free": 2621135,
      "files_total": 2621440,
      "hsm_control_params": [
        {
          "long_description": "Pause HSM coordinator for this filesystem. New requests will be scheduled when coordinator is enabled.",
          "param_key": "mdt.hsm_control",
          "param_value": "disabled",
          "verb": "Disable",
          "mdt": {
            "id": "2",
            "kind": "MDT",
            "resource": "target",
            "conf_params": {
              "lov.qos_prio_free": null,
              "lov.qos_threshold_rr": null,
              "lov.stripecount": null,
              "lov.stripesize": null,
              "mdt.MDS.mds.threads_max": null,
              "mdt.MDS.mds.threads_min": null,
              "mdt.MDS.mds_readpage.threads_max": null,
              "mdt.MDS.mds_readpage.threads_min": null,
              "mdt.MDS.mds_setattr.threads_max": null,
              "mdt.MDS.mds_setattr.threads_min": null,
              "mdt.hsm_control": null
            }
          }
        },
        {
          "long_description": "Enable HSM coordinator for this filesystem.",
          "param_key": "mdt.hsm_control",
          "param_value": "enabled",
          "verb": "Enable",
          "mdt": {
            "id": "2",
            "kind": "MDT",
            "resource": "target",
            "conf_params": {
              "lov.qos_prio_free": null,
              "lov.qos_threshold_rr": null,
              "lov.stripecount": null,
              "lov.stripesize": null,
              "mdt.MDS.mds.threads_max": null,
              "mdt.MDS.mds.threads_min": null,
              "mdt.MDS.mds_readpage.threads_max": null,
              "mdt.MDS.mds_readpage.threads_min": null,
              "mdt.MDS.mds_setattr.threads_max": null,
              "mdt.MDS.mds_setattr.threads_min": null,
              "mdt.hsm_control": null
            }
          }
        },
        {
          "long_description": "Stop HSM coordinator for this filesystem. No new requests may be scheduled.",
          "param_key": "mdt.hsm_control",
          "param_value": "shutdown",
          "verb": "Shutdown",
          "mdt": {
            "id": "2",
            "kind": "MDT",
            "resource": "target",
            "conf_params": {
              "lov.qos_prio_free": null,
              "lov.qos_threshold_rr": null,
              "lov.stripecount": null,
              "lov.stripesize": null,
              "mdt.MDS.mds.threads_max": null,
              "mdt.MDS.mds.threads_min": null,
              "mdt.MDS.mds_readpage.threads_max": null,
              "mdt.MDS.mds_readpage.threads_min": null,
              "mdt.MDS.mds_setattr.threads_max": null,
              "mdt.MDS.mds_setattr.threads_min": null,
              "mdt.hsm_control": null
            }
          }
        }
      ],
      "id": 1,
      "immutable_state": false,
      "label": "fs",
      "mdts": [
        {
          "active_host": "/api/host/1/",
          "active_host_name": "mds1.local",
          "conf_params": {
            "lov.qos_prio_free": null,
            "lov.qos_threshold_rr": null,
            "lov.stripecount": null,
            "lov.stripesize": null,
            "mdt.MDS.mds.threads_max": null,
            "mdt.MDS.mds.threads_min": null,
            "mdt.MDS.mds_readpage.threads_max": null,
            "mdt.MDS.mds_readpage.threads_min": null,
            "mdt.MDS.mds_setattr.threads_max": null,
            "mdt.MDS.mds_setattr.threads_min": null,
            "mdt.hsm_control": null
          },
          "content_type_id": 35,
          "failover_server_name": "mds2.local",
          "failover_servers": [
            "/api/host/2/"
          ],
          "filesystem": "/api/filesystem/1/",
          "filesystem_id": 1,
          "filesystem_name": "fs",
          "filesystems": null,
          "ha_label": "fs-MDT0000_f90e1a",
          "id": 2,
          "immutable_state": false,
          "index": 0,
          "inode_count": 2621440,
          "inode_size": 512,
          "kind": "MDT",
          "label": "fs-MDT0000",
          "name": "fs-MDT0000",
          "primary_server": "/api/host/1/",
          "primary_server_name": "mds1.local",
          "resource_uri": "/api/target/2/",
          "state": "mounted",
          "state_modified_at": "2019-12-10T14:40:01.125881",
          "uuid": "e89ea9fa-9ffc-44ca-b25b-0d9eef0e263c",
          "volume": {
            "filesystem_type": "ext4",
            "id": 1,
            "kind": "Unknown",
            "label": "36001405b9971128dac44fd7a3a837786",
            "resource_uri": "/api/volume/1/",
            "size": 5368709120,
            "status": null,
            "storage_resource": null,
            "usable_for_lustre": true,
            "volume_nodes": []
          },
          "volume_name": "36001405b9971128dac44fd7a3a837786"
        }
      ],
      "mgt": "/api/target/1/",
      "mount_command": "mount -t lustre 10.73.20.12@tcp0:10.73.20.11@tcp0:/fs /mnt/fs",
      "mount_path": "10.73.20.12@tcp0:10.73.20.11@tcp0:/fs",
      "name": "fs",
      "osts": [
        "/api/target/3/",
        "/api/target/4/",
        "/api/target/5/",
        "/api/target/6/",
        "/api/target/7/",
        "/api/target/8/",
        "/api/target/9/",
        "/api/target/10/",
        "/api/target/11/",
        "/api/target/12/",
        "/api/target/13/",
        "/api/target/14/",
        "/api/target/15/",
        "/api/target/16/",
        "/api/target/17/",
        "/api/target/18/",
        "/api/target/19/",
        "/api/target/20/",
        "/api/target/21/",
        "/api/target/22/"
      ],
      "resource_uri": "/api/filesystem/1/",
      "state": "unavailable",
      "state_modified_at": "2020-01-03T18:21:26.777946"
    }
  },
  "host": {
    "1": {
      "address": "mds1.local",
      "boot_time": "2019-12-09T23:11:51",
      "client_mounts": [],
      "content_type_id": 17,
      "corosync_configuration": "/api/corosync_configuration/1/",
      "corosync_ring0": "10.128.0.11",
      "fqdn": "mds1.local",
      "id": 1,
      "immutable_state": false,
      "install_method": "existing_keys_choice",
      "label": "mds1.local",
      "lnet_configuration": "/api/lnet_configuration/1/",
      "member_of_active_filesystem": true,
      "needs_update": true,
      "nids": [
        "10.73.20.11@tcp0"
      ],
      "nodename": "mds1.local",
      "pacemaker_configuration": "/api/pacemaker_configuration/1/",
      "private_key": null,
      "private_key_passphrase": null,
      "resource_uri": "/api/host/1/",
      "root_pw": null,
      "server_profile": {
        "corosync": false,
        "corosync2": true,
        "default": false,
        "initial_state": "managed",
        "managed": true,
        "name": "base_managed_patchless",
        "ntp": true,
        "pacemaker": true,
        "repolist": [
          "base",
          "lustre-server-patchless"
        ],
        "resource_uri": "/api/server_profile/base_managed_patchless/",
        "ui_description": "A storage server suitable for creating new HA-enabled filesystem targets",
        "ui_name": "Managed Storage Server (patchless)",
        "user_selectable": true,
        "worker": false
      },
      "state": "managed",
      "state_modified_at": "2019-12-09T23:15:06.832225"
    },
    "2": {
      "address": "mds2.local",
      "boot_time": "2019-12-09T23:09:56",
      "client_mounts": [],
      "content_type_id": 17,
      "corosync_configuration": "/api/corosync_configuration/2/",
      "corosync_ring0": "10.128.0.12",
      "fqdn": "mds2.local",
      "id": 2,
      "immutable_state": false,
      "install_method": "existing_keys_choice",
      "label": "mds2.local",
      "lnet_configuration": "/api/lnet_configuration/2/",
      "member_of_active_filesystem": true,
      "needs_update": true,
      "nids": [
        "10.73.20.12@tcp0"
      ],
      "nodename": "mds2.local",
      "pacemaker_configuration": "/api/pacemaker_configuration/2/",
      "private_key": null,
      "private_key_passphrase": null,
      "resource_uri": "/api/host/2/",
      "root_pw": null,
      "server_profile": {
        "corosync": false,
        "corosync2": true,
        "default": false,
        "initial_state": "managed",
        "managed": true,
        "name": "base_managed_patchless",
        "ntp": true,
        "pacemaker": true,
        "repolist": [
          "base",
          "lustre-server-patchless"
        ],
        "resource_uri": "/api/server_profile/base_managed_patchless/",
        "ui_description": "A storage server suitable for creating new HA-enabled filesystem targets",
        "ui_name": "Managed Storage Server (patchless)",
        "user_selectable": true,
        "worker": false
      },
      "state": "managed",
      "state_modified_at": "2019-12-09T23:13:17.158537"
    },
    "3": {
      "address": "oss1.local",
      "boot_time": "2019-12-09T23:11:56",
      "client_mounts": [],
      "content_type_id": 17,
      "corosync_configuration": "/api/corosync_configuration/3/",
      "corosync_ring0": "10.128.0.21",
      "fqdn": "oss1.local",
      "id": 3,
      "immutable_state": false,
      "install_method": "existing_keys_choice",
      "label": "oss1.local",
      "lnet_configuration": "/api/lnet_configuration/3/",
      "member_of_active_filesystem": true,
      "needs_update": true,
      "nids": [
        "10.73.20.21@tcp0"
      ],
      "nodename": "oss1.local",
      "pacemaker_configuration": "/api/pacemaker_configuration/3/",
      "private_key": null,
      "private_key_passphrase": null,
      "resource_uri": "/api/host/3/",
      "root_pw": null,
      "server_profile": {
        "corosync": false,
        "corosync2": true,
        "default": false,
        "initial_state": "managed",
        "managed": true,
        "name": "base_managed_patchless",
        "ntp": true,
        "pacemaker": true,
        "repolist": [
          "base",
          "lustre-server-patchless"
        ],
        "resource_uri": "/api/server_profile/base_managed_patchless/",
        "ui_description": "A storage server suitable for creating new HA-enabled filesystem targets",
        "ui_name": "Managed Storage Server (patchless)",
        "user_selectable": true,
        "worker": false
      },
      "state": "managed",
      "state_modified_at": "2019-12-09T23:14:51.479443"
    },
    "4": {
      "address": "oss2.local",
      "boot_time": "2019-12-09T23:12:02",
      "client_mounts": [],
      "content_type_id": 17,
      "corosync_configuration": "/api/corosync_configuration/4/",
      "corosync_ring0": "10.128.0.22",
      "fqdn": "oss2.local",
      "id": 4,
      "immutable_state": false,
      "install_method": "existing_keys_choice",
      "label": "oss2.local",
      "lnet_configuration": "/api/lnet_configuration/4/",
      "member_of_active_filesystem": true,
      "needs_update": true,
      "nids": [
        "10.73.20.22@tcp0"
      ],
      "nodename": "oss2.local",
      "pacemaker_configuration": "/api/pacemaker_configuration/4/",
      "private_key": null,
      "private_key_passphrase": null,
      "resource_uri": "/api/host/4/",
      "root_pw": null,
      "server_profile": {
        "corosync": false,
        "corosync2": true,
        "default": false,
        "initial_state": "managed",
        "managed": true,
        "name": "base_managed_patchless",
        "ntp": true,
        "pacemaker": true,
        "repolist": [
          "base",
          "lustre-server-patchless"
        ],
        "resource_uri": "/api/server_profile/base_managed_patchless/",
        "ui_description": "A storage server suitable for creating new HA-enabled filesystem targets",
        "ui_name": "Managed Storage Server (patchless)",
        "user_selectable": true,
        "worker": false
      },
      "state": "managed",
      "state_modified_at": "2019-12-09T23:14:50.342626"
    },
    "11": {
      "address": "c1",
      "boot_time": "2019-12-09T22:30:46",
      "client_mounts": [],
      "content_type_id": 17,
      "corosync_configuration": null,
      "corosync_ring0": "",
      "fqdn": "c1.local",
      "id": 11,
      "immutable_state": true,
      "install_method": "existing_keys_choice",
      "label": "c1.local",
      "lnet_configuration": "/api/lnet_configuration/11/",
      "member_of_active_filesystem": false,
      "needs_update": false,
      "nids": [],
      "nodename": "c1.local",
      "pacemaker_configuration": null,
      "private_key": null,
      "private_key_passphrase": null,
      "resource_uri": "/api/host/11/",
      "root_pw": null,
      "server_profile": {
        "corosync": false,
        "corosync2": false,
        "default": false,
        "initial_state": "unconfigured",
        "managed": false,
        "name": "default",
        "ntp": false,
        "pacemaker": false,
        "repolist": [
          "base"
        ],
        "resource_uri": "/api/server_profile/default/",
        "ui_description": "An unconfigured server.",
        "ui_name": "Unconfigured Server",
        "user_selectable": false,
        "worker": false
      },
      "state": "unconfigured",
      "state_modified_at": "2020-01-03T23:17:49.723627"
    }
  },
  "lnet_configuration": {
    "1": {
      "id": 1,
      "state": "lnet_up",
      "host_id": 1,
      "immutable_state": false,
      "not_deleted": true,
      "content_type_id": 52,
      "state_modified_at": "1990-12-31T23:59:60Z"
    },
    "2": {
      "id": 2,
      "state": "lnet_up",
      "host_id": 2,
      "immutable_state": false,
      "not_deleted": true,
      "content_type_id": 52,
      "state_modified_at": "1990-12-31T23:59:60Z"
    },
    "3": {
      "id": 3,
      "state": "lnet_up",
      "host_id": 3,
      "immutable_state": false,
      "not_deleted": true,
      "content_type_id": 52,
      "state_modified_at": "1990-12-31T23:59:60Z"
    },
    "4": {
      "id": 4,
      "state": "lnet_up",
      "host_id": 4,
      "immutable_state": false,
      "not_deleted": true,
      "content_type_id": 52,
      "state_modified_at": "1990-12-31T23:59:60Z"
    },
    "11": {
      "id": 11,
      "state": "unconfigured",
      "host_id": 11,
      "immutable_state": false,
      "not_deleted": true,
      "content_type_id": 52,
      "state_modified_at": "1990-12-31T23:59:60Z"
    }
  },
  "managed_target_mount": {
    "1": {
      "id": 1,
      "host_id": 2,
      "mount_point": "/mnt/MGS",
      "volume_node_id": 6,
      "primary": true,
      "target_id": 1,
      "not_deleted": true
    },
    "2": {
      "id": 2,
      "host_id": 1,
      "mount_point": "/mnt/MGS",
      "volume_node_id": 2,
      "primary": false,
      "target_id": 1,
      "not_deleted": true
    },
    "3": {
      "id": 3,
      "host_id": 1,
      "mount_point": "/mnt/fs-MDT0000",
      "volume_node_id": 4,
      "primary": true,
      "target_id": 2,
      "not_deleted": true
    },
    "4": {
      "id": 4,
      "host_id": 2,
      "mount_point": "/mnt/fs-MDT0000",
      "volume_node_id": 8,
      "primary": false,
      "target_id": 2,
      "not_deleted": true
    },
    "5": {
      "id": 5,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0000",
      "volume_node_id": 135,
      "primary": true,
      "target_id": 3,
      "not_deleted": true
    },
    "6": {
      "id": 6,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0000",
      "volume_node_id": 179,
      "primary": false,
      "target_id": 3,
      "not_deleted": true
    },
    "7": {
      "id": 7,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0001",
      "volume_node_id": 197,
      "primary": true,
      "target_id": 4,
      "not_deleted": true
    },
    "8": {
      "id": 8,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0001",
      "volume_node_id": 152,
      "primary": false,
      "target_id": 4,
      "not_deleted": true
    },
    "9": {
      "id": 9,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0002",
      "volume_node_id": 146,
      "primary": true,
      "target_id": 5,
      "not_deleted": true
    },
    "10": {
      "id": 10,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0002",
      "volume_node_id": 190,
      "primary": false,
      "target_id": 5,
      "not_deleted": true
    },
    "11": {
      "id": 11,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0003",
      "volume_node_id": 191,
      "primary": true,
      "target_id": 6,
      "not_deleted": true
    },
    "12": {
      "id": 12,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0003",
      "volume_node_id": 147,
      "primary": false,
      "target_id": 6,
      "not_deleted": true
    },
    "13": {
      "id": 13,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0004",
      "volume_node_id": 91,
      "primary": true,
      "target_id": 7,
      "not_deleted": true
    },
    "14": {
      "id": 14,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0004",
      "volume_node_id": 111,
      "primary": false,
      "target_id": 7,
      "not_deleted": true
    },
    "15": {
      "id": 15,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0005",
      "volume_node_id": 94,
      "primary": true,
      "target_id": 8,
      "not_deleted": true
    },
    "16": {
      "id": 16,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0005",
      "volume_node_id": 75,
      "primary": false,
      "target_id": 8,
      "not_deleted": true
    },
    "17": {
      "id": 17,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0006",
      "volume_node_id": 83,
      "primary": true,
      "target_id": 9,
      "not_deleted": true
    },
    "18": {
      "id": 18,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0006",
      "volume_node_id": 102,
      "primary": false,
      "target_id": 9,
      "not_deleted": true
    },
    "19": {
      "id": 19,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0007",
      "volume_node_id": 100,
      "primary": true,
      "target_id": 10,
      "not_deleted": true
    },
    "20": {
      "id": 20,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0007",
      "volume_node_id": 82,
      "primary": false,
      "target_id": 10,
      "not_deleted": true
    },
    "21": {
      "id": 21,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0008",
      "volume_node_id": 86,
      "primary": true,
      "target_id": 11,
      "not_deleted": true
    },
    "22": {
      "id": 22,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0008",
      "volume_node_id": 105,
      "primary": false,
      "target_id": 11,
      "not_deleted": true
    },
    "23": {
      "id": 23,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0009",
      "volume_node_id": 108,
      "primary": true,
      "target_id": 12,
      "not_deleted": true
    },
    "24": {
      "id": 24,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0009",
      "volume_node_id": 88,
      "primary": false,
      "target_id": 12,
      "not_deleted": true
    },
    "25": {
      "id": 25,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000a",
      "volume_node_id": 143,
      "primary": true,
      "target_id": 13,
      "not_deleted": true
    },
    "26": {
      "id": 26,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000a",
      "volume_node_id": 187,
      "primary": false,
      "target_id": 13,
      "not_deleted": true
    },
    "27": {
      "id": 27,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000b",
      "volume_node_id": 169,
      "primary": true,
      "target_id": 14,
      "not_deleted": true
    },
    "28": {
      "id": 28,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000b",
      "volume_node_id": 149,
      "primary": false,
      "target_id": 14,
      "not_deleted": true
    },
    "29": {
      "id": 29,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000c",
      "volume_node_id": 140,
      "primary": true,
      "target_id": 15,
      "not_deleted": true
    },
    "30": {
      "id": 30,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000c",
      "volume_node_id": 161,
      "primary": false,
      "target_id": 15,
      "not_deleted": true
    },
    "31": {
      "id": 31,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000d",
      "volume_node_id": 157,
      "primary": true,
      "target_id": 16,
      "not_deleted": true
    },
    "32": {
      "id": 32,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000d",
      "volume_node_id": 137,
      "primary": false,
      "target_id": 16,
      "not_deleted": true
    },
    "33": {
      "id": 33,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000e",
      "volume_node_id": 77,
      "primary": true,
      "target_id": 17,
      "not_deleted": true
    },
    "34": {
      "id": 34,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000e",
      "volume_node_id": 96,
      "primary": false,
      "target_id": 17,
      "not_deleted": true
    },
    "35": {
      "id": 35,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST000f",
      "volume_node_id": 196,
      "primary": true,
      "target_id": 18,
      "not_deleted": true
    },
    "36": {
      "id": 36,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST000f",
      "volume_node_id": 153,
      "primary": false,
      "target_id": 18,
      "not_deleted": true
    },
    "37": {
      "id": 37,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0010",
      "volume_node_id": 80,
      "primary": true,
      "target_id": 19,
      "not_deleted": true
    },
    "38": {
      "id": 38,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0010",
      "volume_node_id": 99,
      "primary": false,
      "target_id": 19,
      "not_deleted": true
    },
    "39": {
      "id": 39,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0011",
      "volume_node_id": 98,
      "primary": true,
      "target_id": 20,
      "not_deleted": true
    },
    "40": {
      "id": 40,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0011",
      "volume_node_id": 79,
      "primary": false,
      "target_id": 20,
      "not_deleted": true
    },
    "41": {
      "id": 41,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0012",
      "volume_node_id": 90,
      "primary": true,
      "target_id": 21,
      "not_deleted": true
    },
    "42": {
      "id": 42,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0012",
      "volume_node_id": 110,
      "primary": false,
      "target_id": 21,
      "not_deleted": true
    },
    "43": {
      "id": 43,
      "host_id": 4,
      "mount_point": "/mnt/fs-OST0013",
      "volume_node_id": 104,
      "primary": true,
      "target_id": 22,
      "not_deleted": true
    },
    "44": {
      "id": 44,
      "host_id": 3,
      "mount_point": "/mnt/fs-OST0013",
      "volume_node_id": 85,
      "primary": false,
      "target_id": 22,
      "not_deleted": true
    }
  },
  "ost_pool": {
    "18": {
      "id": 18,
      "name": "pool",
      "filesystem_id": 1,
      "not_deleted": true,
      "content_type_id": 41
    }
  },
  "ost_pool_osts": {
    "18": {
      "id": 18,
      "ostpool_id": 18,
      "managedost_id": 13
    },
    "19": {
      "id": 19,
      "ostpool_id": 18,
      "managedost_id": 14
    }
  },
  "stratagem_config": {},
  "target": {
    "1": {
      "active_host": "/api/host/2/",
      "active_host_name": "mds2.local",
      "conf_params": null,
      "content_type_id": 28,
      "failover_server_name": "mds1.local",
      "failover_servers": [
        "/api/host/1/"
      ],
      "filesystem": null,
      "filesystem_id": null,
      "filesystem_name": null,
      "filesystems": [
        {
          "id": 1,
          "name": "fs"
        }
      ],
      "ha_label": "MGS_d45eef",
      "id": 1,
      "immutable_state": false,
      "index": null,
      "inode_count": 32768,
      "inode_size": 256,
      "kind": "MGT",
      "label": "MGS",
      "name": "MGS",
      "primary_server": "/api/host/2/",
      "primary_server_name": "mds2.local",
      "resource_uri": "/api/target/1/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:39:42.817660",
      "uuid": "21ee7e09-2829-47df-b06b-55b536a56cad",
      "volume": "/api/volume/3/",
      "volume_name": "36001405e6b55c7571cb45a7b4a29aa0f"
    },
    "2": {
      "active_host": "/api/host/1/",
      "active_host_name": "mds1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 35,
      "failover_server_name": "mds2.local",
      "failover_servers": [
        "/api/host/2/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-MDT0000_f90e1a",
      "id": 2,
      "immutable_state": false,
      "index": 0,
      "inode_count": 2621440,
      "inode_size": 512,
      "kind": "MDT",
      "label": "fs-MDT0000",
      "name": "fs-MDT0000",
      "primary_server": "/api/host/1/",
      "primary_server_name": "mds1.local",
      "resource_uri": "/api/target/2/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:01.125881",
      "uuid": "e89ea9fa-9ffc-44ca-b25b-0d9eef0e263c",
      "volume": "/api/volume/1/",
      "volume_name": "36001405b9971128dac44fd7a3a837786"
    },
    "3": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0000_1d09cf",
      "id": 3,
      "immutable_state": false,
      "index": 0,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0000",
      "name": "fs-OST0000",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/3/",
      "state": "mounted",
      "state_modified_at": "2020-01-03T03:57:23.503118",
      "uuid": "e946eace-4d1a-4a62-9bef-1f0f36e13f50",
      "volume": "/api/volume/67/",
      "volume_name": "360014050a4658e570b74f22a763a221e"
    },
    "4": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0001_dbea04",
      "id": 4,
      "immutable_state": false,
      "index": 1,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0001",
      "name": "fs-OST0001",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/4/",
      "state": "mounted",
      "state_modified_at": "2020-01-03T03:57:29.997150",
      "uuid": "2c300fc5-8221-483b-bda2-388d85f5e2f7",
      "volume": "/api/volume/64/",
      "volume_name": "3600140524b803577dd94719af82ed682"
    },
    "5": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0002_53c57d",
      "id": 5,
      "immutable_state": false,
      "index": 2,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0002",
      "name": "fs-OST0002",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/5/",
      "state": "mounted",
      "state_modified_at": "2020-01-03T03:56:23.744466",
      "uuid": "7d0747e0-6fd7-4096-bf38-64e6cccd891a",
      "volume": "/api/volume/58/",
      "volume_name": "36001405367a5e6565834e2cac41766cf"
    },
    "6": {
      "active_host": null,
      "active_host_name": "---",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0003_b73317",
      "id": 6,
      "immutable_state": false,
      "index": 3,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0003",
      "name": "fs-OST0003",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/6/",
      "state": "unmounted",
      "state_modified_at": "2020-01-03T18:21:26.493369",
      "uuid": "dd7a0389-ec99-475c-9ada-01f71a25cbb8",
      "volume": "/api/volume/59/",
      "volume_name": "3600140537ddcd70c2654c8ba9326b9d0"
    },
    "7": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0004_2cc476",
      "id": 7,
      "immutable_state": false,
      "index": 4,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0004",
      "name": "fs-OST0004",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/7/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:45.071433",
      "uuid": "4f2c5a47-3635-4d43-b5f4-17d809057c09",
      "volume": "/api/volume/32/",
      "volume_name": "36001405579c6ebc3487451ea0fd2ada6"
    },
    "8": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0005_b732f9",
      "id": 8,
      "immutable_state": false,
      "index": 5,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0005",
      "name": "fs-OST0005",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/8/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:45.831734",
      "uuid": "c0b0a685-d6ad-4932-a75f-3b8729d32175",
      "volume": "/api/volume/35/",
      "volume_name": "3600140563ce7820116541f4b39e14ceb"
    },
    "9": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0006_ae9110",
      "id": 9,
      "immutable_state": false,
      "index": 6,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0006",
      "name": "fs-OST0006",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/9/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:49.257108",
      "uuid": "575bc2aa-97a6-4dd7-8547-a6cbc28c1919",
      "volume": "/api/volume/42/",
      "volume_name": "360014057333de8e31ad4324a07037bd2"
    },
    "10": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0007_6610df",
      "id": 10,
      "immutable_state": false,
      "index": 7,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0007",
      "name": "fs-OST0007",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/10/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:50.414241",
      "uuid": "0020c06a-34b4-449d-a2e6-821a5a282376",
      "volume": "/api/volume/41/",
      "volume_name": "36001405756559e490324c469979f7875"
    },
    "11": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0008_11c056",
      "id": 11,
      "immutable_state": false,
      "index": 8,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0008",
      "name": "fs-OST0008",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/11/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:48.425809",
      "uuid": "6ba7c341-cfa0-4521-ab90-2544ebbed6d3",
      "volume": "/api/volume/27/",
      "volume_name": "3600140584f613cf36834bc982e7d20a5"
    },
    "12": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0009_2a6334",
      "id": 12,
      "immutable_state": false,
      "index": 9,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0009",
      "name": "fs-OST0009",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/12/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:51.249963",
      "uuid": "74794e8f-c0b4-47c2-8b72-4485568d1d5b",
      "volume": "/api/volume/29/",
      "volume_name": "360014058cfb7526b6ae4f38b8b625c80"
    },
    "13": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000a_17d2a4",
      "id": 13,
      "immutable_state": false,
      "index": 10,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000a",
      "name": "fs-OST000a",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/13/",
      "state": "mounted",
      "state_modified_at": "2019-12-29T17:55:55.079826",
      "uuid": "f9b4b8ab-e7aa-49c1-8ebc-308850370d59",
      "volume": "/api/volume/75/",
      "volume_name": "36001405a4bb53f5272f474fb2a8def3a"
    },
    "14": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000b_7efa3d",
      "id": 14,
      "immutable_state": false,
      "index": 11,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000b",
      "name": "fs-OST000b",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/14/",
      "state": "mounted",
      "state_modified_at": "2019-12-16T14:02:36.339837",
      "uuid": "ed397732-aae4-4b6c-92a2-5ad6493406f2",
      "volume": "/api/volume/61/",
      "volume_name": "36001405b350e59779b3451ab4f2133c0"
    },
    "15": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000c_36572d",
      "id": 15,
      "immutable_state": false,
      "index": 12,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000c",
      "name": "fs-OST000c",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/15/",
      "state": "mounted",
      "state_modified_at": "2019-12-16T14:02:37.256962",
      "uuid": "77ca77a4-25b7-4d75-b4ed-cb4bd7136c6c",
      "volume": "/api/volume/72/",
      "volume_name": "36001405b996d5e380df4c169fd2cced0"
    },
    "16": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000d_ce67cd",
      "id": 16,
      "immutable_state": false,
      "index": 13,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000d",
      "name": "fs-OST000d",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/16/",
      "state": "mounted",
      "state_modified_at": "2019-12-16T14:02:37.677632",
      "uuid": "ca33ca87-0d80-44a7-8da1-7fa494e563c2",
      "volume": "/api/volume/69/",
      "volume_name": "36001405ba240ba85ed44dbe8c88a7255"
    },
    "17": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000e_795f37",
      "id": 17,
      "immutable_state": false,
      "index": 14,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000e",
      "name": "fs-OST000e",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/17/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:42.981999",
      "uuid": "b6158d5d-f6c7-4773-9865-9817e989db9c",
      "volume": "/api/volume/36/",
      "volume_name": "36001405c1b415e51ae646399a004c8a6"
    },
    "18": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST000f_9f88be",
      "id": 18,
      "immutable_state": false,
      "index": 15,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST000f",
      "name": "fs-OST000f",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/18/",
      "state": "mounted",
      "state_modified_at": "2020-01-03T03:57:16.763630",
      "uuid": "42b636fb-3783-40cf-b6a6-764b7c864ce1",
      "volume": "/api/volume/65/",
      "volume_name": "36001405c2b98662137c46ed83ed7152f"
    },
    "19": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0010_245a89",
      "id": 19,
      "immutable_state": false,
      "index": 16,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0010",
      "name": "fs-OST0010",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/19/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:48.845289",
      "uuid": "8875ae65-98da-4c54-b15c-996d5ddb6011",
      "volume": "/api/volume/39/",
      "volume_name": "36001405c76660a2252246f6a13f6009d"
    },
    "20": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0011_429991",
      "id": 20,
      "immutable_state": false,
      "index": 17,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0011",
      "name": "fs-OST0011",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/20/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:43.671214",
      "uuid": "aec28c50-bdf5-4a6b-9e61-b9887c665846",
      "volume": "/api/volume/38/",
      "volume_name": "36001405c7ca9e653a76430b8c6db2abe"
    },
    "21": {
      "active_host": "/api/host/3/",
      "active_host_name": "oss1.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss2.local",
      "failover_servers": [
        "/api/host/4/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0012_111136",
      "id": 21,
      "immutable_state": false,
      "index": 18,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0012",
      "name": "fs-OST0012",
      "primary_server": "/api/host/3/",
      "primary_server_name": "oss1.local",
      "resource_uri": "/api/target/21/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:46.236980",
      "uuid": "466eeff0-3b11-4a08-ab18-50c63f230242",
      "volume": "/api/volume/31/",
      "volume_name": "36001405ee1f6934cae44fd38df0def14"
    },
    "22": {
      "active_host": "/api/host/4/",
      "active_host_name": "oss2.local",
      "conf_params": {
        "lov.qos_prio_free": null,
        "lov.qos_threshold_rr": null,
        "lov.stripecount": null,
        "lov.stripesize": null,
        "mdt.MDS.mds.threads_max": null,
        "mdt.MDS.mds.threads_min": null,
        "mdt.MDS.mds_readpage.threads_max": null,
        "mdt.MDS.mds_readpage.threads_min": null,
        "mdt.MDS.mds_setattr.threads_max": null,
        "mdt.MDS.mds_setattr.threads_min": null,
        "mdt.hsm_control": null
      },
      "content_type_id": 51,
      "failover_server_name": "oss1.local",
      "failover_servers": [
        "/api/host/3/"
      ],
      "filesystem": "/api/filesystem/1/",
      "filesystem_id": 1,
      "filesystem_name": "fs",
      "filesystems": null,
      "ha_label": "fs-OST0013_132abb",
      "id": 22,
      "immutable_state": false,
      "index": 19,
      "inode_count": 327680,
      "inode_size": 512,
      "kind": "OST",
      "label": "fs-OST0013",
      "name": "fs-OST0013",
      "primary_server": "/api/host/4/",
      "primary_server_name": "oss2.local",
      "resource_uri": "/api/target/22/",
      "state": "mounted",
      "state_modified_at": "2019-12-10T14:40:44.657528",
      "uuid": "bec7b8a8-2e28-4bb4-9ad1-51735a3bc5bc",
      "volume": "/api/volume/28/",
      "volume_name": "36001405f0f88ac938b9401daadf69904"
    }
  },
  "volume": {
    "52": {
      "filesystem_type": "mpath_member",
      "id": 52,
      "kind": "SCSI device",
      "label": "36001405639d22d0f25f412c9deaffad9",
      "resource_uri": "/api/volume/52/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/318/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/1/",
          "host_id": 1,
          "host_label": "mds1.local",
          "id": 132,
          "path": "/dev/mapper/mpathd",
          "primary": true,
          "resource_uri": "/api/volume_node/132/",
          "use": true,
          "volume_id": 52
        },
        {
          "host": "/api/host/2/",
          "host_id": 2,
          "host_label": "mds2.local",
          "id": 176,
          "path": "/dev/mapper/mpathd",
          "primary": false,
          "resource_uri": "/api/volume_node/176/",
          "use": true,
          "volume_id": 52
        }
      ]
    },
    "53": {
      "filesystem_type": "mpath_member",
      "id": 53,
      "kind": "SCSI device",
      "label": "36001405b9971128dac44fd7a3a837786",
      "resource_uri": "/api/volume/53/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/319/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/1/",
          "host_id": 1,
          "host_label": "mds1.local",
          "id": 133,
          "path": "/dev/mapper/mpathc",
          "primary": true,
          "resource_uri": "/api/volume_node/133/",
          "use": true,
          "volume_id": 53
        },
        {
          "host": "/api/host/2/",
          "host_id": 2,
          "host_label": "mds2.local",
          "id": 177,
          "path": "/dev/mapper/mpathc",
          "primary": false,
          "resource_uri": "/api/volume_node/177/",
          "use": true,
          "volume_id": 53
        }
      ]
    },
    "54": {
      "filesystem_type": "mpath_member",
      "id": 54,
      "kind": "SCSI device",
      "label": "360014057bdce1c58e374dccaabbc4954",
      "resource_uri": "/api/volume/54/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/317/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/1/",
          "host_id": 1,
          "host_label": "mds1.local",
          "id": 130,
          "path": "/dev/mapper/mpathb",
          "primary": false,
          "resource_uri": "/api/volume_node/130/",
          "use": true,
          "volume_id": 54
        },
        {
          "host": "/api/host/2/",
          "host_id": 2,
          "host_label": "mds2.local",
          "id": 174,
          "path": "/dev/mapper/mpathb",
          "primary": true,
          "resource_uri": "/api/volume_node/174/",
          "use": true,
          "volume_id": 54
        }
      ]
    },
    "55": {
      "filesystem_type": "mpath_member",
      "id": 55,
      "kind": "SCSI device",
      "label": "36001405e6b55c7571cb45a7b4a29aa0f",
      "resource_uri": "/api/volume/55/",
      "size": 536870912,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/316/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/1/",
          "host_id": 1,
          "host_label": "mds1.local",
          "id": 131,
          "path": "/dev/mapper/mpatha",
          "primary": false,
          "resource_uri": "/api/volume_node/131/",
          "use": true,
          "volume_id": 55
        },
        {
          "host": "/api/host/2/",
          "host_id": 2,
          "host_label": "mds2.local",
          "id": 175,
          "path": "/dev/mapper/mpatha",
          "primary": true,
          "resource_uri": "/api/volume_node/175/",
          "use": true,
          "volume_id": 55
        }
      ]
    },
    "56": {
      "filesystem_type": "mpath_member",
      "id": 56,
      "kind": "SCSI device",
      "label": "36001405f0f88ac938b9401daadf69904",
      "resource_uri": "/api/volume/56/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/334/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 144,
          "path": "/dev/mapper/mpatht",
          "primary": false,
          "resource_uri": "/api/volume_node/144/",
          "use": true,
          "volume_id": 56
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 164,
          "path": "/dev/mapper/mpatht",
          "primary": true,
          "resource_uri": "/api/volume_node/164/",
          "use": true,
          "volume_id": 56
        }
      ]
    },
    "57": {
      "filesystem_type": "mpath_member",
      "id": 57,
      "kind": "SCSI device",
      "label": "3600140584f613cf36834bc982e7d20a5",
      "resource_uri": "/api/volume/57/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/348/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 145,
          "path": "/dev/mapper/mpaths",
          "primary": true,
          "resource_uri": "/api/volume_node/145/",
          "use": true,
          "volume_id": 57
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 165,
          "path": "/dev/mapper/mpaths",
          "primary": false,
          "resource_uri": "/api/volume_node/165/",
          "use": true,
          "volume_id": 57
        }
      ]
    },
    "58": {
      "filesystem_type": "mpath_member",
      "id": 58,
      "kind": "SCSI device",
      "label": "36001405367a5e6565834e2cac41766cf",
      "resource_uri": "/api/volume/58/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/341/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 146,
          "path": "/dev/mapper/mpathb",
          "primary": true,
          "resource_uri": "/api/volume_node/146/",
          "use": true,
          "volume_id": 58
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 166,
          "path": "/dev/mapper/mpathb",
          "primary": false,
          "resource_uri": "/api/volume_node/166/",
          "use": true,
          "volume_id": 58
        }
      ]
    },
    "59": {
      "filesystem_type": "mpath_member",
      "id": 59,
      "kind": "SCSI device",
      "label": "3600140537ddcd70c2654c8ba9326b9d0",
      "resource_uri": "/api/volume/59/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/351/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 147,
          "path": "/dev/mapper/mpatha",
          "primary": false,
          "resource_uri": "/api/volume_node/147/",
          "use": true,
          "volume_id": 59
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 167,
          "path": "/dev/mapper/mpatha",
          "primary": true,
          "resource_uri": "/api/volume_node/167/",
          "use": true,
          "volume_id": 59
        }
      ]
    },
    "60": {
      "filesystem_type": "mpath_member",
      "id": 60,
      "kind": "SCSI device",
      "label": "360014058cfb7526b6ae4f38b8b625c80",
      "resource_uri": "/api/volume/60/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/342/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 148,
          "path": "/dev/mapper/mpathn",
          "primary": false,
          "resource_uri": "/api/volume_node/148/",
          "use": true,
          "volume_id": 60
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 168,
          "path": "/dev/mapper/mpathn",
          "primary": true,
          "resource_uri": "/api/volume_node/168/",
          "use": true,
          "volume_id": 60
        }
      ]
    },
    "61": {
      "filesystem_type": "mpath_member",
      "id": 61,
      "kind": "SCSI device",
      "label": "36001405b350e59779b3451ab4f2133c0",
      "resource_uri": "/api/volume/61/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/340/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 149,
          "path": "/dev/mapper/mpathm",
          "primary": false,
          "resource_uri": "/api/volume_node/149/",
          "use": true,
          "volume_id": 61
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 169,
          "path": "/dev/mapper/mpathm",
          "primary": true,
          "resource_uri": "/api/volume_node/169/",
          "use": true,
          "volume_id": 61
        }
      ]
    },
    "62": {
      "filesystem_type": "mpath_member",
      "id": 62,
      "kind": "SCSI device",
      "label": "36001405ee1f6934cae44fd38df0def14",
      "resource_uri": "/api/volume/62/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/336/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 150,
          "path": "/dev/mapper/mpathp",
          "primary": true,
          "resource_uri": "/api/volume_node/150/",
          "use": true,
          "volume_id": 62
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 170,
          "path": "/dev/mapper/mpathp",
          "primary": false,
          "resource_uri": "/api/volume_node/170/",
          "use": true,
          "volume_id": 62
        }
      ]
    },
    "63": {
      "filesystem_type": "mpath_member",
      "id": 63,
      "kind": "SCSI device",
      "label": "36001405579c6ebc3487451ea0fd2ada6",
      "resource_uri": "/api/volume/63/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/349/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 151,
          "path": "/dev/mapper/mpatho",
          "primary": true,
          "resource_uri": "/api/volume_node/151/",
          "use": true,
          "volume_id": 63
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 171,
          "path": "/dev/mapper/mpatho",
          "primary": false,
          "resource_uri": "/api/volume_node/171/",
          "use": true,
          "volume_id": 63
        }
      ]
    },
    "64": {
      "filesystem_type": "mpath_member",
      "id": 64,
      "kind": "SCSI device",
      "label": "3600140524b803577dd94719af82ed682",
      "resource_uri": "/api/volume/64/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/339/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 152,
          "path": "/dev/mapper/mpathq",
          "primary": false,
          "resource_uri": "/api/volume_node/152/",
          "use": true,
          "volume_id": 64
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 173,
          "path": "/dev/mapper/mpathq",
          "primary": true,
          "resource_uri": "/api/volume_node/173/",
          "use": true,
          "volume_id": 64
        }
      ]
    },
    "65": {
      "filesystem_type": "mpath_member",
      "id": 65,
      "kind": "SCSI device",
      "label": "36001405c2b98662137c46ed83ed7152f",
      "resource_uri": "/api/volume/65/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/347/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 153,
          "path": "/dev/mapper/mpathr",
          "primary": false,
          "resource_uri": "/api/volume_node/153/",
          "use": true,
          "volume_id": 65
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 172,
          "path": "/dev/mapper/mpathr",
          "primary": true,
          "resource_uri": "/api/volume_node/172/",
          "use": true,
          "volume_id": 65
        }
      ]
    },
    "66": {
      "filesystem_type": "mpath_member",
      "id": 66,
      "kind": "SCSI device",
      "label": "3600140563ce7820116541f4b39e14ceb",
      "resource_uri": "/api/volume/66/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/333/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 134,
          "path": "/dev/mapper/mpathd",
          "primary": false,
          "resource_uri": "/api/volume_node/134/",
          "use": true,
          "volume_id": 66
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 154,
          "path": "/dev/mapper/mpathd",
          "primary": true,
          "resource_uri": "/api/volume_node/154/",
          "use": true,
          "volume_id": 66
        }
      ]
    },
    "67": {
      "filesystem_type": "mpath_member",
      "id": 67,
      "kind": "SCSI device",
      "label": "360014050a4658e570b74f22a763a221e",
      "resource_uri": "/api/volume/67/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/344/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 135,
          "path": "/dev/mapper/mpathc",
          "primary": true,
          "resource_uri": "/api/volume_node/135/",
          "use": true,
          "volume_id": 67
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 155,
          "path": "/dev/mapper/mpathc",
          "primary": false,
          "resource_uri": "/api/volume_node/155/",
          "use": true,
          "volume_id": 67
        }
      ]
    },
    "68": {
      "filesystem_type": "mpath_member",
      "id": 68,
      "kind": "SCSI device",
      "label": "36001405c1b415e51ae646399a004c8a6",
      "resource_uri": "/api/volume/68/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/332/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 136,
          "path": "/dev/mapper/mpathf",
          "primary": true,
          "resource_uri": "/api/volume_node/136/",
          "use": true,
          "volume_id": 68
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 156,
          "path": "/dev/mapper/mpathf",
          "primary": false,
          "resource_uri": "/api/volume_node/156/",
          "use": true,
          "volume_id": 68
        }
      ]
    },
    "69": {
      "filesystem_type": "mpath_member",
      "id": 69,
      "kind": "SCSI device",
      "label": "36001405ba240ba85ed44dbe8c88a7255",
      "resource_uri": "/api/volume/69/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/346/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 137,
          "path": "/dev/mapper/mpathe",
          "primary": false,
          "resource_uri": "/api/volume_node/137/",
          "use": true,
          "volume_id": 69
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 157,
          "path": "/dev/mapper/mpathe",
          "primary": true,
          "resource_uri": "/api/volume_node/157/",
          "use": true,
          "volume_id": 69
        }
      ]
    },
    "70": {
      "filesystem_type": "mpath_member",
      "id": 70,
      "kind": "SCSI device",
      "label": "36001405c7ca9e653a76430b8c6db2abe",
      "resource_uri": "/api/volume/70/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/345/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 138,
          "path": "/dev/mapper/mpathh",
          "primary": false,
          "resource_uri": "/api/volume_node/138/",
          "use": true,
          "volume_id": 70
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 158,
          "path": "/dev/mapper/mpathh",
          "primary": true,
          "resource_uri": "/api/volume_node/158/",
          "use": true,
          "volume_id": 70
        }
      ]
    },
    "71": {
      "filesystem_type": "mpath_member",
      "id": 71,
      "kind": "SCSI device",
      "label": "36001405c76660a2252246f6a13f6009d",
      "resource_uri": "/api/volume/71/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/343/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 139,
          "path": "/dev/mapper/mpathg",
          "primary": true,
          "resource_uri": "/api/volume_node/139/",
          "use": true,
          "volume_id": 71
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 159,
          "path": "/dev/mapper/mpathg",
          "primary": false,
          "resource_uri": "/api/volume_node/159/",
          "use": true,
          "volume_id": 71
        }
      ]
    },
    "72": {
      "filesystem_type": "mpath_member",
      "id": 72,
      "kind": "SCSI device",
      "label": "36001405b996d5e380df4c169fd2cced0",
      "resource_uri": "/api/volume/72/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/335/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 140,
          "path": "/dev/mapper/mpathj",
          "primary": true,
          "resource_uri": "/api/volume_node/140/",
          "use": true,
          "volume_id": 72
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 161,
          "path": "/dev/mapper/mpathj",
          "primary": false,
          "resource_uri": "/api/volume_node/161/",
          "use": true,
          "volume_id": 72
        }
      ]
    },
    "73": {
      "filesystem_type": "mpath_member",
      "id": 73,
      "kind": "SCSI device",
      "label": "36001405756559e490324c469979f7875",
      "resource_uri": "/api/volume/73/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/337/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 141,
          "path": "/dev/mapper/mpathi",
          "primary": false,
          "resource_uri": "/api/volume_node/141/",
          "use": true,
          "volume_id": 73
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 160,
          "path": "/dev/mapper/mpathi",
          "primary": true,
          "resource_uri": "/api/volume_node/160/",
          "use": true,
          "volume_id": 73
        }
      ]
    },
    "74": {
      "filesystem_type": "mpath_member",
      "id": 74,
      "kind": "SCSI device",
      "label": "360014057333de8e31ad4324a07037bd2",
      "resource_uri": "/api/volume/74/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/338/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 142,
          "path": "/dev/mapper/mpathl",
          "primary": true,
          "resource_uri": "/api/volume_node/142/",
          "use": true,
          "volume_id": 74
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 162,
          "path": "/dev/mapper/mpathl",
          "primary": false,
          "resource_uri": "/api/volume_node/162/",
          "use": true,
          "volume_id": 74
        }
      ]
    },
    "75": {
      "filesystem_type": "mpath_member",
      "id": 75,
      "kind": "SCSI device",
      "label": "36001405a4bb53f5272f474fb2a8def3a",
      "resource_uri": "/api/volume/75/",
      "size": 5368709120,
      "status": "configured-ha",
      "storage_resource": "/api/storage_resource/350/",
      "usable_for_lustre": true,
      "volume_nodes": [
        {
          "host": "/api/host/3/",
          "host_id": 3,
          "host_label": "oss1.local",
          "id": 143,
          "path": "/dev/mapper/mpathk",
          "primary": true,
          "resource_uri": "/api/volume_node/143/",
          "use": true,
          "volume_id": 75
        },
        {
          "host": "/api/host/4/",
          "host_id": 4,
          "host_label": "oss2.local",
          "id": 163,
          "path": "/dev/mapper/mpathk",
          "primary": false,
          "resource_uri": "/api/volume_node/163/",
          "use": true,
          "volume_id": 75
        }
      ]
    }
  },
  "volume_node": {
    "130": {
      "id": 130,
      "volume_id": 54,
      "host_id": 1,
      "path": "/dev/mapper/mpathb",
      "storage_resource_id": 326,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "131": {
      "id": 131,
      "volume_id": 55,
      "host_id": 1,
      "path": "/dev/mapper/mpatha",
      "storage_resource_id": 327,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "132": {
      "id": 132,
      "volume_id": 52,
      "host_id": 1,
      "path": "/dev/mapper/mpathd",
      "storage_resource_id": 328,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "133": {
      "id": 133,
      "volume_id": 53,
      "host_id": 1,
      "path": "/dev/mapper/mpathc",
      "storage_resource_id": 329,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "134": {
      "id": 134,
      "volume_id": 66,
      "host_id": 3,
      "path": "/dev/mapper/mpathd",
      "storage_resource_id": 374,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "135": {
      "id": 135,
      "volume_id": 67,
      "host_id": 3,
      "path": "/dev/mapper/mpathc",
      "storage_resource_id": 375,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "136": {
      "id": 136,
      "volume_id": 68,
      "host_id": 3,
      "path": "/dev/mapper/mpathf",
      "storage_resource_id": 376,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "137": {
      "id": 137,
      "volume_id": 69,
      "host_id": 3,
      "path": "/dev/mapper/mpathe",
      "storage_resource_id": 377,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "138": {
      "id": 138,
      "volume_id": 70,
      "host_id": 3,
      "path": "/dev/mapper/mpathh",
      "storage_resource_id": 378,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "139": {
      "id": 139,
      "volume_id": 71,
      "host_id": 3,
      "path": "/dev/mapper/mpathg",
      "storage_resource_id": 379,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "140": {
      "id": 140,
      "volume_id": 72,
      "host_id": 3,
      "path": "/dev/mapper/mpathj",
      "storage_resource_id": 380,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "141": {
      "id": 141,
      "volume_id": 73,
      "host_id": 3,
      "path": "/dev/mapper/mpathi",
      "storage_resource_id": 381,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "142": {
      "id": 142,
      "volume_id": 74,
      "host_id": 3,
      "path": "/dev/mapper/mpathl",
      "storage_resource_id": 382,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "143": {
      "id": 143,
      "volume_id": 75,
      "host_id": 3,
      "path": "/dev/mapper/mpathk",
      "storage_resource_id": 383,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "144": {
      "id": 144,
      "volume_id": 56,
      "host_id": 3,
      "path": "/dev/mapper/mpatht",
      "storage_resource_id": 384,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "145": {
      "id": 145,
      "volume_id": 57,
      "host_id": 3,
      "path": "/dev/mapper/mpaths",
      "storage_resource_id": 385,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "146": {
      "id": 146,
      "volume_id": 58,
      "host_id": 3,
      "path": "/dev/mapper/mpathb",
      "storage_resource_id": 386,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "147": {
      "id": 147,
      "volume_id": 59,
      "host_id": 3,
      "path": "/dev/mapper/mpatha",
      "storage_resource_id": 387,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "148": {
      "id": 148,
      "volume_id": 60,
      "host_id": 3,
      "path": "/dev/mapper/mpathn",
      "storage_resource_id": 388,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "149": {
      "id": 149,
      "volume_id": 61,
      "host_id": 3,
      "path": "/dev/mapper/mpathm",
      "storage_resource_id": 389,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "150": {
      "id": 150,
      "volume_id": 62,
      "host_id": 3,
      "path": "/dev/mapper/mpathp",
      "storage_resource_id": 390,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "151": {
      "id": 151,
      "volume_id": 63,
      "host_id": 3,
      "path": "/dev/mapper/mpatho",
      "storage_resource_id": 391,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "152": {
      "id": 152,
      "volume_id": 64,
      "host_id": 3,
      "path": "/dev/mapper/mpathq",
      "storage_resource_id": 392,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "153": {
      "id": 153,
      "volume_id": 65,
      "host_id": 3,
      "path": "/dev/mapper/mpathr",
      "storage_resource_id": 393,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "174": {
      "id": 174,
      "volume_id": 54,
      "host_id": 2,
      "path": "/dev/mapper/mpathb",
      "storage_resource_id": 444,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "175": {
      "id": 175,
      "volume_id": 55,
      "host_id": 2,
      "path": "/dev/mapper/mpatha",
      "storage_resource_id": 445,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "176": {
      "id": 176,
      "volume_id": 52,
      "host_id": 2,
      "path": "/dev/mapper/mpathd",
      "storage_resource_id": 446,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "177": {
      "id": 177,
      "volume_id": 53,
      "host_id": 2,
      "path": "/dev/mapper/mpathc",
      "storage_resource_id": 447,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "178": {
      "id": 178,
      "volume_id": 66,
      "host_id": 4,
      "path": "/dev/mapper/mpathd",
      "storage_resource_id": 472,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "179": {
      "id": 179,
      "volume_id": 67,
      "host_id": 4,
      "path": "/dev/mapper/mpathc",
      "storage_resource_id": 473,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "180": {
      "id": 180,
      "volume_id": 68,
      "host_id": 4,
      "path": "/dev/mapper/mpathf",
      "storage_resource_id": 474,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "181": {
      "id": 181,
      "volume_id": 69,
      "host_id": 4,
      "path": "/dev/mapper/mpathe",
      "storage_resource_id": 475,
      "primary": false,
      "use": false,
      "not_deleted": true
    },
    "182": {
      "id": 182,
      "volume_id": 70,
      "host_id": 4,
      "path": "/dev/mapper/mpathh",
      "storage_resource_id": 476,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "183": {
      "id": 183,
      "volume_id": 71,
      "host_id": 4,
      "path": "/dev/mapper/mpathg",
      "storage_resource_id": 477,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "184": {
      "id": 184,
      "volume_id": 73,
      "host_id": 4,
      "path": "/dev/mapper/mpathi",
      "storage_resource_id": 478,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "185": {
      "id": 185,
      "volume_id": 72,
      "host_id": 4,
      "path": "/dev/mapper/mpathj",
      "storage_resource_id": 479,
      "primary": false,
      "use": false,
      "not_deleted": true
    },
    "186": {
      "id": 186,
      "volume_id": 74,
      "host_id": 4,
      "path": "/dev/mapper/mpathl",
      "storage_resource_id": 480,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "187": {
      "id": 187,
      "volume_id": 75,
      "host_id": 4,
      "path": "/dev/mapper/mpathk",
      "storage_resource_id": 481,
      "primary": false,
      "use": false,
      "not_deleted": true
    },
    "188": {
      "id": 188,
      "volume_id": 56,
      "host_id": 4,
      "path": "/dev/mapper/mpatht",
      "storage_resource_id": 482,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "189": {
      "id": 189,
      "volume_id": 57,
      "host_id": 4,
      "path": "/dev/mapper/mpaths",
      "storage_resource_id": 483,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "190": {
      "id": 190,
      "volume_id": 58,
      "host_id": 4,
      "path": "/dev/mapper/mpathb",
      "storage_resource_id": 484,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "191": {
      "id": 191,
      "volume_id": 59,
      "host_id": 4,
      "path": "/dev/mapper/mpatha",
      "storage_resource_id": 485,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "192": {
      "id": 192,
      "volume_id": 60,
      "host_id": 4,
      "path": "/dev/mapper/mpathn",
      "storage_resource_id": 486,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "193": {
      "id": 193,
      "volume_id": 61,
      "host_id": 4,
      "path": "/dev/mapper/mpathm",
      "storage_resource_id": 487,
      "primary": false,
      "use": false,
      "not_deleted": true
    },
    "194": {
      "id": 194,
      "volume_id": 62,
      "host_id": 4,
      "path": "/dev/mapper/mpathp",
      "storage_resource_id": 488,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "195": {
      "id": 195,
      "volume_id": 63,
      "host_id": 4,
      "path": "/dev/mapper/mpatho",
      "storage_resource_id": 489,
      "primary": false,
      "use": true,
      "not_deleted": true
    },
    "196": {
      "id": 196,
      "volume_id": 65,
      "host_id": 4,
      "path": "/dev/mapper/mpathr",
      "storage_resource_id": 490,
      "primary": true,
      "use": true,
      "not_deleted": true
    },
    "197": {
      "id": 197,
      "volume_id": 64,
      "host_id": 4,
      "path": "/dev/mapper/mpathq",
      "storage_resource_id": 491,
      "primary": true,
      "use": true,
      "not_deleted": true
    }
  }
}
    "#;

    serde_json::from_str(&data).unwrap()
}
