#!/usr/bin/env python

import os
import subprocess


def psql_sql(sql):
    p = subprocess.Popen(["psql", "-h", "postgres", "-U", "chroma", "-tAc {}".format(sql)], stdout=subprocess.PIPE)
    return p.stdout.read()


out = psql_sql(
    "SELECT 'CREATE DATABASE grafana' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'grafana')\\gexec"
)
print("Create grafana db if not already created: {}".format(out))
