#!/usr/bin/env python

import sys
import json

profile_output = sys.argv[1]
metafiles = sys.argv[2:]

with open("%s.template" % profile_output) as f:
    profile = json.load(f)

for metafile in metafiles:
    if 'template' in metafile:
        continue
    with open(metafile) as f:
        meta = json.load(f)
    profile['bundles'].append(meta['name'])
    if 'packages' in meta:
        profile['packages'][meta['name']] = meta['packages']

with open(profile_output, "w") as f:
    json.dump(profile, f, indent=2)
