#!/bin/bash -ex

. tests/framework/utils/defaults.sh
. tests/framework/utils/selective_auto_pass.sh
. tests/framework/utils/cleanup.sh

set_defaults true
check_for_autopass

export CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:-"chroma/tests/framework/integration/shared_storage_configuration/full_cluster/shared_storage_configuration_cluster_cfg.json"}

cd $WORKSPACE
curl -f -k -O "$JOB_URL/chroma-bundles/$ARCHIVE_NAME"

got_aborted=false
# Gather logs from nodes and release the cluster at exit
trap "set +e; cleanup" EXIT

trap "set -x
got_aborted=true
echo \"Got SIGTERM\"
ps axf
exit 1" TERM

chroma/tests/framework/utils/provisioner_interface/provision_cluster

eval $(python chroma/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

echo "Beginning automated test run..."
export MEASURE_COVERAGE=$MEASURE_COVERAGE
chroma/tests/framework/integration/upgrade_os/cluster_setup
chroma/tests/framework/integration/upgrade_os/run_tests
echo "Automated test run complete."

# Combine coverage reports from the different nodes.
if $MEASURE_COVERAGE; then
  ls .coverage*
  # https://github.com/pypa/virtualenv/issues/355
  python_version=$(python -c 'import platform; print ".".join(platform.python_version_tuple()[0:2])')
  echo "
[paths]
source1 =
    $WORKSPACE/chroma/chroma-manager/
    /usr/share/chroma-manager/
source2 =
    $WORKSPACE/chroma/chroma-agent/chroma_agent/
    /usr/lib/python$python_version/site-packages/chroma_agent/

[report]
include =
    $WORKSPACE/chroma/*
omit =
    *junk.py
    */tests/*
" > .coveragerc

  coverage combine
  coverage report -m
  coverage xml --ignore-errors
fi
