#!/bin/bash -e

PROVISIONER=${PROVISIONER:-"ssh chromatest@autotest ./provisionchroma -v -S"}

. chroma-manager/tests/framework/utils/defaults.sh
set_defaults false

export CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:-"chroma/chroma-manager/tests/framework/services/services_cluster_config.json"}

# Get the chroma-externals repo as pip is going to need it
scripts/update_chroma-externals.py

cd $WORKSPACE/chroma_test_env/chroma/chroma-manager

# Release the provisioned cluster (at the exit of this script)
trap "chroma/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster" EXIT

# Provision cluster to run tests on
cd $WORKSPACE/chroma_test_env/
chroma/chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster

eval $(python chroma/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

pdsh -R ssh -l root -S -w $CHROMA_MANAGER $TEST_RUNNER "exec 2>&1; set -xe
cd /etc/yum.repos.d/
for f in *.repo; do
  sed -i -e \"s/distro=${TEST_DISTRO_NAME}${TEST_DISTRO_VERSION}/distro=$JENKINS_DISTRO/\" -e 's/http:\/\/jenkins-pull/https:\/\/jenkins-pull/g' \$f
done" | dshbak -c
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

# we should get the cluster fully configured from the provisioner, but we don't
ssh root@$CHROMA_MANAGER <<EOF
set -ex
# Install non-python/pipable dependencies
yum install -y python-virtualenv
EOF

echo "Beginning automated test run..."
chroma/chroma-manager/tests/framework/services/cluster_setup
chroma/chroma-manager/tests/framework/services/run_tests
echo "Automated test run complete."

# Combine coverage reports from the different nodes.
if $MEASURE_COVERAGE; then
  echo "
[paths]
source1 =
    $WORKSPACE/chroma/
    /home/chromatest/chroma_test_env/chroma/

[report]
include =
    $WORKSPACE/chroma/*
omit =
    *junk.py
    */tests/*
" > .coveragerc

  coverage combine
  coverage report -m
  coverage xml --ignore-errors
fi
