NAME		:= socket.io-client
VERSION		:= 0.9.16
SHA1SUM		:= 4da7515c5e773041d1b423970415bcc430f35fc6
DEPENDENCIES	:= xmlhttprequest uglify-js ws active-x-obfuscator

include ../include/Makefile.rpm-from-npm
