# HYD-3324 temporary fix because the original location is offline and we need
# a way forwards. This is Chris Gearing's dropbox.
# The immediate need after we move forwards is to fix our build system so everything
# is local with external references being pull local independent of the build.
LOCATION := https://dl.dropboxusercontent.com/s/8ui2ao371ak94xf/gevent-1.0rc2.tar.gz
REQUIREMENT := $(LOCATION)

include ../include/Makefile.rpm-from-tarball
