include $(CURDIR)/../../include/Makefile.version
RPMS		:= chroma-agent-management
EXCLUDES	:= lustre
DESC		:= $(PRODUCT_NAME) Agent
NAME		:= $(SHORT_PRODUCT_NAME)-agent
VERSION		:= $(PACKAGE_VERSION)

include ../include/Makefile.bundle
