ALTER TABLE IF EXISTS corosync_target_resource RENAME CONSTRAINT corosync_target_resource_cluster_id_fkey TO corosync_resource_cluster_id_fkey;
ALTER TABLE IF EXISTS corosync_target_resource RENAME TO corosync_resource;
ALTER INDEX IF EXISTS corosync_target_resource_id_idx RENAME TO corosync_resource_id_idx;
ALTER INDEX IF EXISTS corosync_target_resource_id_cluster_id_key RENAME TO corosync_resource_id_cluster_id_key;

ALTER TABLE IF EXISTS corosync_target_resource_host RENAME CONSTRAINT corosync_target_resource_host_cluster_id_corosync_resource_fkey TO corosync_resource_host_cluster_id_corosync_resource_fkey;
ALTER TABLE IF EXISTS corosync_target_resource_host RENAME CONSTRAINT corosync_target_resource_host_host_id_fkey TO corosync_resource_host_host_id_fkey;
ALTER TABLE IF EXISTS corosync_target_resource_host RENAME TO corosync_resource_host;
ALTER INDEX IF EXISTS corosync_target_resource_host_id_corosync_resource_id__key RENAME TO corosync_resource_host_id_corosync_resource_id__key;
