LOCATION      := http://ftp.redhat.com/redhat/linux/enterprise/6Server/en/os/SRPMS/pacemaker-1.1.12-4.el6.src.rpm
RPMBUILD_OPTS := "--without publican"
REQUIREMENT :=

include ../include/Makefile.rpm
