SRC_REPO = http://dl.fedoraproject.org/pub/epel/6/x86_64/

ALL_RPMS = django-picklefield-0.1.9-2.el6.noarch.rpm Django-south-0.7.5-1.el6.noarch.rpm pcapy-0.10.5-6.el6.x86_64.rpm pyparsing-1.5.6-1.el6.noarch.rpm python-argparse-1.2.1-2.el6.noarch.rpm python-daemon-1.5.2-1.el6.noarch.rpm python-importlib-1.0.2-1.el6.noarch.rpm python-lockfile-0.8-3.el6.noarch.rpm python-meld3-0.6.7-1.el6.x86_64.rpm python-netifaces-0.5-1.el6.x86_64.rpm python-ordereddict-1.1-2.el6.noarch.rpm

include ../include/Makefile.fetch-from-repo
