#PLAT_NAME	:= $(shell $(TOP)/include/platform_info --name)
#PLAT_VERSION	:= $(shell $(TOP)/include/platform_info --release)
#PLAT_BUILD_OK	:= $(shell $(TOP)/include/platform_info --buildok $(CURDIR))
PLAT_NAME      := centos
PLAT_VERSION   := 6.3
PLAT_BUILD_OK  := true

# Don't use platform in _topdir for Jenkins builds
#ifeq ('$(WORKSPACE)', '')
#RPM_TOP		:= $(TOP)/_topdir/$(PLAT_NAME)-$(PLAT_VERSION)
#else
#RPM_TOP		:= $(TOP)/_topdir
#endif
RPM_TOP		:= $(CURDIR)/$(PLAT_VERSION)
RPM_DIR		:= $(RPM_TOP)/RPMS
SRPM_DIR	:= $(RPM_TOP)/SRPMS
RPM_LAST_BUILT	:= $(RPM_DIR)/.last_built
