ifeq ($(shell uname -s),Darwin)
    # For OSX we are using Python 2.7 so pretend to be EL7.
    EL_MAJOR        := 7
else
    EL_MAJOR = $(shell rpm --eval '%{?rhel}')
endif

ifeq ($(EL_MAJOR), 7)
DISTRO			:= el7
DISTRO_TAG		:= el7
else ifeq ($(EL_MAJOR), 6)
DISTRO			:= el6.8
DISTRO_TAG		:= el6
else
$(error "Unknown major el version $(EL_MAJOR)")
endif
