EL_MAJOR = $(shell rpm --eval '%{?rhel}')
ifeq ($(EL_MAJOR), 7)
DISTRO			:= el7
DISTRO_TAG		:= el7
else ifeq ($(EL_MAJOR), 6)
DISTRO			:= el6.7
DISTRO_TAG		:= el6
else
$(error "Unknown major el version $(EL_MAJOR)")
endif
