requirements:
	if [ -n "$(REQUIREMENT)" ]; then                                                   \
		if [[ a$(REQUIREMENT) == ahttp://* ]]; then                                \
			echo "$(patsubst %==*,%,$(REQUIREMENT))" >> ../../chroma-manager/requirements.tmp; \
		else                                                                       \
			echo "$(REQUIREMENT)" >> ../../chroma-manager/requirements.tmp;                    \
		fi;                                                                        \
	fi
