E2FSPROGS_RELEASE = 1.42.3.wc3-7
SRC_REPO = http://downloads.whamcloud.com/public/e2fsprogs/1.42.3.wc3/el6/RPMS/x86_64/

ALL_RPMS = e2fsprogs-$(E2FSPROGS_RELEASE).el6.x86_64.rpm e2fsprogs-libs-$(E2FSPROGS_RELEASE).el6.x86_64.rpm libcom_err-$(E2FSPROGS_RELEASE).el6.x86_64.rpm libss-$(E2FSPROGS_RELEASE).el6.x86_64.rpm

include ../include/Makefile.fetch-from-repo
