LOCATION := http://pypi.python.org/packages/source/k/kombu/kombu-2.4.7.tar.gz
DEPS := amqplib anyjson # from-EL6: python-msgpack python-setuptools python2-devel

include ../include/Makefile.rpm-from-tarball
