LOCATION := http://pypi.python.org/packages/source/k/kombu/kombu-3.0.19.tar.gz
DEPS := amqp anyjson # from-EL6: python-msgpack python-setuptools python2-devel

include ../include/Makefile.rpm-from-tarball
