{
 "title": "Target MDT Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "target_name" },
   { "name": "object_or_files_title" }
  ]
 },
 "panels": [
  {
   "title": "Metadata Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select difference(samples) from target WHERE \"units\"='\"reqs\"' AND \"kind\" = '\"MDT\"' AND \"name\" =~ /\"close\"|\"getattr\"|\"getxattr\"|\"link\"|\"mkdir\"|\"mknod\"|\"open\"|\"rename\"|\"rmdir\"|\"setattr\"|\"statfs\"|\"unlink\"/ AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Space Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((mean(\"bytes_total\") - mean(\"bytes_free\")) / mean(\"bytes_total\") * 100) FROM \"target\" WHERE  \"target\"='\"$target_name\"' AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$object_or_files_title Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Files Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((mean(\"files_total\") - mean(\"files_free\")) / mean(\"files_total\") * 100) AS \"FilesUsed\" FROM \"target\" WHERE  \"target\"='\"$target_name\"' AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}