#!/usr/bin/env bash
set -eu

/bin/mkdir -p /etc/iml

until /usr/bin/docker cp iml_nginx.1.$(/usr/bin/docker service ps -f "name=iml_nginx.1" iml_nginx -q --no-trunc 2>/dev/null | head -n1):/var/lib/chroma/iml-settings.conf /etc/iml/iml-settings.conf 2>/dev/null; do
    echo "copy-embedded-settings: Waiting for EMF startup..."
    sleep 5
done
