#!/usr/bin/env python

import re

vars = {
    "SSL_PATH": "/var/lib/chroma",
    "HTTPS_FRONTEND_PORT": "7443",
    "HTTP_API_PROXY_PASS": "http://gunicorn:8001",
    "HTTP_AGENT_PROXY_PASS": "http://http-agent:8002",
    "HTTP_AGENT2_PROXY_PASS": "http://emf-agent-comms:8003",
    "REPO_PATH": "/var/lib/chroma/repo",
    "DEVICE_AGGREGATOR_PROXY_PASS": "http://device:8008",
    "WARP_DRIVE_PROXY_PASS": "http://emf-warp-drive:8890",
    "MAILBOX_PROXY_PASS": "http://emf-mailbox:8891",
    "GRAFANA_PROXY_PASS": "http://grafana:3000",
    "INFLUXDB_PROXY_PASS": "http://influxdb:8086",
    "EMF_API_PROXY_PASS": "http://emf-api:8004",
    "REPORT_PATH": "/var/spool/emf/report",
    "REPORT_PROXY_PASS": "http://emf-report:8893",
}

conf_template = "./chroma-manager.conf.template"

with open(conf_template, "r") as f:
    config = f.read()

    config = re.sub(r"proxy_pass {{(.+)}}(.*);", r"proxy_pass {{\g<1>}}\g<2>;", config)
    config = re.sub(
        r"proxy_read_timeout (.+);",
        r"proxy_read_timeout \g<1>;\n    resolver 127.0.0.11 ipv6=off valid=5s;\n    resolver_timeout 5s;",
        config,
    )

    for (k, v) in vars.iteritems():
        config = config.replace("{{%s}}" % k, v)

    config = re.sub(r"{{(.+)}}", r"{{ .Env.\g<1> }}", config)

    with open("emf.template", "w") as f2:
        f2.write(config)
