#!/bin/bash

# Authors:
#  Andrew Beekhof <abeekhof@redhat.com>
#  Fabio M. Di Nitto <fdinitto@redhat.com>
#
# License: Revised BSD

# chkconfig: - 20 80
# description: Corosync Cluster Engine
# processname: corosync
#
### BEGIN INIT INFO
# Provides:		corosync
# Required-Start:	$network $syslog
# Required-Stop:	$network $syslog
# Default-Start:
# Default-Stop:
# Short-Description:	Starts and stops Corosync Cluster Engine.
# Description:		Starts and stops Corosync Cluster Engine.
### END INIT INFO

desc="Corosync Cluster Engine"
prog="corosync"

# set secure PATH
PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/sbin"

success()
{
	echo -ne "[  OK  ]\r"
}

failure()
{
	echo -ne "[FAILED]\r"
}

status()
{
	pid=$(pidof $1 2>/dev/null)
	rtrn=$?
	if [ $rtrn -ne 0 ]; then
		echo "$1 is stopped"
	else
		echo "$1 (pid $pid) is running..."
	fi
	return $rtrn
}

# rpm based distros
if [ -d /etc/sysconfig ]; then
	[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions
	[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
	[ -z "$LOCK_FILE" ] && LOCK_FILE="/var/lock/subsys/$prog"
fi

# deb based distros
if [ -d /etc/default ]; then
	[ -f /etc/default/$prog ] && . /etc/default/$prog
	[ -z "$LOCK_FILE" ] && LOCK_FILE="/var/lock/$prog"
fi

# The version of __pids_pidof in /etc/init.d/functions calls pidof with -x
# This means it matches scripts, including this one.
# Redefine it here so that status (from the same file) works.
# Otherwise simultaneous calls to stop() will loop forever
__pids_pidof() {
        pidof -c -o $$ -o $PPID -o %PPID "$1" || \
                pidof -c -o $$ -o $PPID -o %PPID "${1##*/}"
}

cluster_disabled_at_boot()
{
       if grep -q nocluster /proc/cmdline && \
          [ "$(tty)" = "/dev/console" ]; then
               echo -e "not configured to run at boot"
               failure
               return 1
       fi
       return 0
}

start()
{
        ipaddr=$(ip addr list dev eth0 | sed -ne '/inet /s/  *inet \(.*\)\/.*/\1/p' | head -1)
        ed <<EOF /etc/corosync/corosync.conf >/dev/null 2>&1
/bindnetaddr/s/: .*/: $ipaddr/
w
q
EOF
	echo -n "Starting $desc ($prog): "

	! cluster_disabled_at_boot && return

	# most recent distributions use tmpfs for /var/run
	# to avoid to clean it up on every boot.
	# they also assume that init scripts will create
	# required subdirectories for proper operations
	mkdir -p /var/run

	if status $prog > /dev/null 2>&1; then
		success
	else
		$prog > /dev/null 2>&1

		# give it time to fail
		sleep 2
		if status $prog > /dev/null 2>&1; then
			touch $LOCK_FILE
			success
		else
			failure
			rtrn=1
		fi
	fi
	echo
}

executed_by_cman()
{
	[ -f /var/run/cman.pid ] || return 0

	read cman_pid foo < /var/run/cman.pid
	if [ "$(pidof $prog)" == "$cman_pid" ];then
		echo -n "$desc was executed by cman"
		failure
		echo
		return 1
	fi

	return 0
}

stop()
{
	! status $prog > /dev/null 2>&1 && return

	! executed_by_cman && return

	echo -n "Signaling $desc ($prog) to terminate: "
	kill -TERM $(pidof $prog) > /dev/null 2>&1
	success
	echo

	echo -n "Waiting for $prog services to unload:"
	while status $prog > /dev/null 2>&1; do
		sleep 1
		echo -n "."
	done

	rm -f $LOCK_FILE
	success
	echo
}

restart()
{
	stop
	start
}

rtrn=0

case "$1" in
start)
	start
;;
restart|reload|force-reload)
	restart
;;
condrestart|try-restart)
	if status $prog > /dev/null 2>&1; then
		restart
	fi
;;
status)
	status $prog
	rtrn=$?
;;
stop)
	stop
;;
*)
	echo "usage: $0 {start|stop|restart|reload|force-reload|condrestart|try-restart|status}"
	rtrn=2
;;
esac

exit $rtrn
