#!/bin/bash -ex

if [[ $slave = rhel$(rpm --eval %rhel)\&\&* ]]; then
    RHEL=true
else
    RHEL=false
fi

spacelist_to_commalist() {
    echo $@ | tr ' ' ','
}

[ -r localenv ] && . localenv

# Remove test results and coverage reports from previous run
rm -rfv $PWD/test_reports/*
rm -rfv $PWD/coverage_reports/.coverage*
mkdir -p $PWD/test_reports
mkdir -p $PWD/coverage_reports

ARCHIVE_NAME=$SHORT_ARCHIVE_NAME-$IEEL_VERSION-current.tar.gz
CLUSTER_CONFIG=${CLUSTER_CONFIG:-"$(ls $PWD/shared_storage_configuration_cluster_cfg.json)"}
CHROMA_DIR=${CHROMA_DIR:-"$PWD/chroma/"}
USE_FENCE_XVM=false

eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

TESTS=${TESTS:-"tests/integration/installation_and_upgrade/"}

trap "set +e; echo 'Collecting reports...'; scp root@$TEST_RUNNER:~/test_report*.xml \"$PWD/test_reports/\"" EXIT

# Install and setup chroma software storage appliances
pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]}) "exec 2>&1; set -xe
# Ensure that coverage is disabled
rm -f /usr/lib/python2.6/site-packages/sitecustomize.py*

if $USE_FENCE_XVM; then
    # fence_xvm support
    mkdir -p /etc/cluster
    echo \"not secure\" > /etc/cluster/fence_xvm.key
fi" | dshbak -c
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

if [ -z "$JENKINS_PULL" ]; then
    JENKINS_PULL="2cf9b55238c654b00bc37a6e8ccc4caf"
fi
# first fetch and install chroma 2.4.1.4
BUILD_JOB=ieel-b2_4
BUILD_NUM=8
set +x
echo "++ curl -s -k -u \"${JENKINS_USER}:**********\" \"${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/api/xml?xpath=*/artifact/fileName&wrapper=foo\"
++ sed -e 's/.*>\([i]\?ee[l]\?-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/')"
IEEL_FROM_ARCHIVE=$(curl -s -k -u "${JENKINS_USER}:${JENKINS_PULL}" "${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/api/xml?xpath=*/artifact/fileName&wrapper=foo" | sed -e 's/.*>\([i]\?ee[l]\?-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/')
set -x
IEEL_FROM_VER="${IEEL_FROM_ARCHIVE#*-}"
IEEL_FROM_VER="${IEEL_FROM_VER%.tar.gz}"
set +x
echo "+ curl -k -O -u \"${JENKINS_USER}:***********\" \"${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/artifact/$IEEL_FROM_ARCHIVE\""
curl -k -O -u "${JENKINS_USER}:${JENKINS_PULL}" "${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/artifact/$IEEL_FROM_ARCHIVE"
set -x

# Install and setup old chroma manager
scp $IEEL_FROM_ARCHIVE $CHROMA_DIR/chroma-manager/tests/utils/install.exp root@$CHROMA_MANAGER:/tmp
ssh root@$CHROMA_MANAGER "#don't do this, it hangs the ssh up, when used with expect, for some reason: exec 2>&1
set -ex
yum -y install expect
# Install from the installation package
cd /tmp
tar xzvf $IEEL_FROM_ARCHIVE
cd ${IEEL_FROM_ARCHIVE%%.tar.gz}
if ! expect ../install.exp $CHROMA_USER $CHROMA_EMAIL $CHROMA_PASS ${CHROMA_NTP_SERVER:-localhost}; then
    rc=\${PIPESTATUS[0]}
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit \$rc
fi"
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

# Install and setup chroma software storage appliances
pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]}) "exec 2>&1; set -xe
# if this node uses the Intel proxies, make sure the agent is doing so
if [ -f /etc/profile.d/intel_proxy.sh ]; then
    echo \". /etc/profile.d/intel_proxy.sh\" > /etc/sysconfig/chroma-agent
    # IEEL prior to 2.4.2.0 can't set proxies in the chroma-agent environment
    # so we have to configure it to use the proxy with subscription-manager
    if [ ${IEEL_FROM_VER//./} -lt 2420 ] && which subscription-manager; then
        proxy=\$(sed -ne '/^export http_proxy=/s/.*\"\(.*\)\"\$/\1/p' /etc/profile.d/intel_proxy.sh)
        [[ \$proxy =~ \/\/([^:]{1,}):{0,1}([[:digit:]]{1,}) ]]
        subscription-manager config --server.proxy_hostname=\${BASH_REMATCH[1]} --server.proxy_port=\${BASH_REMATCH[2]}
    fi
fi" | dshbak -c

echo "Create and exercise a filesystem..."

ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x ~/test_report_pre_upgrade.xml $TESTS/../shared_storage_configuration/test_cluster_setup.py $TESTS/test_update_with_yum.py:TestYumUpdate.test_create"

echo "Now upgrade the OS and IML..."

# first have to shut down the filesystem so that we don't have incompatible OS/IML issues
ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x ~/test_report_post_filesystem_stop.xml $TESTS/test_update_with_yum.py:TestYumUpdate.test_stop_before_update"

. $CHROMA_DIR/chroma-manager/tests/framework/integration/utils/upgrade_os.sh
upgrade_os $TEST_DISTRO_NAME $UPGRADE_DISTRO_VERSION $(spacelist_to_commalist $CHROMA_MANAGER ${STORAGE_APPLIANCES[@]} ${WORKERS[@]})

# Install and setup chroma manager
scp $ARCHIVE_NAME $CHROMA_DIR/chroma-manager/tests/utils/upgrade.exp root@$CHROMA_MANAGER:/tmp
ssh root@$CHROMA_MANAGER "#don't do this, it hangs the ssh up, when used with expect, for some reason: exec 2>&1
set -ex
existing_IML_version=\$(rpm -q --qf \"%{VERSION}-%{RELEASE}\n\" chroma-manager)
# Install from the installation package
cd /tmp
tar xzvf $ARCHIVE_NAME
cd $(basename $ARCHIVE_NAME -current.tar.gz)

echo \"First without access to YUM repos\"

ips=\$(grep -e ^base -e ^mirror /etc/yum.repos.d/* | sed -e 's/.*:\/\/\([^/]*\)\/.*/\1/g' -e 's/:.*//' | sort -u | while read n; do getent ahosts \$n | sed -ne 's/\(.*\)  STREAM .*/\1/p'; done | sort -u)
for ip in \$ips; do
    iptables -I OUTPUT -d \$ip -p tcp --dport 80 -j REJECT
done
iptables -L -nv

if expect ../upgrade.exp; then
    echo \"Installation unexpectedly succeeded without access to repos\"
    for ip in \$ips; do
        iptables -D OUTPUT -d \$ip -p tcp --dport 80 -j REJECT
    done
    exit 1
fi
for ip in \$ips; do
    if ! iptables -D OUTPUT -d \$ip -p tcp --dport 80 -j REJECT; then
        rc=\${PIPESTATUS[0]}
        iptables -L -nv
        exit \$rc
    fi
done

echo \"Now with EPEL configured\"

cat <<EOF > /etc/yum.repos.d/epel.repo
[epel]
name=epel
baseurl=http://${COBBLER_SERVER:-10.14.80.10}/cobbler/repo_mirror/addon-epel6-x86_64/
enabled=1
priority=1
gpgcheck=0
sslverify=0
EOF
yum makecache

if expect ../upgrade.exp; then
    echo \"Installation unexpectedly succeeded with EPEL configured\"
    rm -f /etc/yum.repos.d/epel.repo
    exit 1
fi
rm -f /etc/yum.repos.d/epel.repo

if $RHEL; then
    release=\$(lsb_release -sr || sed -n -e '1s/.* release \(.*\) .*/\1/p' /etc/issue)
    yum-config-manager --disable  rhel-6-server-optional-rpms,RHEL-\$release-optional-x86_64
    # let's also remove any local RH optional repo
    if grep \"RHEL-6\.[0-9]-optional-x86_64\" /etc/yum.repos.d/cobbler-config.repo; then
        ed <<\"EOF\" /etc/yum.repos.d/cobbler-config.repo
/\[RHEL-6\.[0-9]-optional-x86_64\]/;/^$/d
wq
EOF
    fi
fi

if ! expect ../upgrade.exp; then
    rc=\${PIPESTATUS[0]}
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit \$rc
fi
# make sure it really did do an upgrade
upgraded_IML_version=\$(rpm -q --qf \"%{VERSION}-%{RELEASE}\n\" chroma-manager)
if [ \$existing_IML_version = \$upgraded_IML_version ]; then
    echo \"Upgrade didn't actually upgrade the chroma-manager package\"
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit 1
fi
# install cman here to test that the fence-agents-iml package is being a
# "duck-like" replacement for fence-agents since cman depends on
# fence-agents
yum -y install cman

cat <<\"EOF1\" > /usr/share/chroma-manager/local_settings.py
import logging
LOG_LEVEL = logging.DEBUG
$LOCAL_SETTINGS
EOF1

# Ensure that coverage is disabled
rm -f /usr/lib/python2.6/site-packages/sitecustomize.py*"

echo "End upgrade and setup."

echo "Test existing filesystem is still there"

TESTS="$TESTS/test_update_with_yum.py:TestYumUpdate.test_no_retired_repos \
       $TESTS/test_update_with_yum.py:TestYumUpdate.test_yum_update \
       $TESTS/test_create_filesystem.py:TestExistsFilesystem.test_exists"

ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x ~/test_report_post_upgrade.xml $TESTS"

# test that removing the chroma-manager RPM removes /var/lib/chroma
ssh root@$CHROMA_MANAGER "set -xe
exec 2>&1
ls -l /var/lib/chroma
rpm -e chroma-manager-cli chroma-manager chroma-manager-libs
if [ -d /var/lib/chroma ]; then
    echo \"Removing RPMs failed to clean up /var/lib/chroma\"
    ls -l /var/lib/chroma
    exit 1
fi"

exit 0
