#!/bin/bash -ex

if [[ $slave = rhel$(rpm --eval %rhel)\&\&* ]]; then
    RHEL=true
else
    RHEL=false
fi

spacelist_to_commalist() {
    echo $@ | tr ' ' ','
}

[ -r localenv ] && . localenv

# Remove test results and coverage reports from previous run
rm -rfv $PWD/test_reports/*
rm -rfv $PWD/coverage_reports/.coverage*
mkdir -p $PWD/test_reports
mkdir -p $PWD/coverage_reports

ARCHIVE_NAME=ieel-$IEEL_VERSION-current.tar.gz
CLUSTER_CONFIG=${CLUSTER_CONFIG:-"$(ls $PWD/shared_storage_configuration_cluster_cfg.json)"}
CHROMA_DIR=${CHROMA_DIR:-"$PWD/chroma/"}
USE_FENCE_XVM=false

PREVIOUS_INSTALL_DIR=previous_install
UPGRADE_INSTALL_DIR=upgrade_install

eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

TESTS_DIR="tests/integration/installation_and_upgrade/"

trap "set +e; echo 'Collecting reports...'; scp root@$TEST_RUNNER:~/test_report*.xml \"$PWD/test_reports/\"" EXIT

# Install and setup chroma software storage appliances
pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]}) "exec 2>&1; set -xe
# Ensure that coverage is disabled
# https://github.com/pypa/virtualenv/issues/355
python_version=\$(python -c 'import platform; print \".\".join(platform.python_version_tuple()[0:2])')
rm -f /usr/lib/python\$python_version/site-packages/sitecustomize.py*

if $USE_FENCE_XVM; then
    # fence_xvm support
    mkdir -p /etc/cluster
    echo \"not secure\" > /etc/cluster/fence_xvm.key
fi" | dshbak -c
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

if [ -z "$JENKINS_PULL" ]; then
    JENKINS_PULL="2cf9b55238c654b00bc37a6e8ccc4caf"
fi
# first fetch and install chroma 2.4.1.2
BUILD_JOB=chroma-blessed
BUILD_NUM=125
set +x
echo "++ curl -s -k -u \"${JENKINS_USER}:**********\" \"${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/arch=x86_64,distro=$JENKINS_DISTRO/api/xml?xpath=*/artifact/fileName&wrapper=foo\"
++ sed -e 's/.*>\(ieel-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/')"
IEEL_FROM_ARCHIVE=$(curl -s -k -u "${JENKINS_USER}:${JENKINS_PULL}" "${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/arch=x86_64,distro=$JENKINS_DISTRO/api/xml?xpath=*/artifact/fileName&wrapper=foo" | sed -e 's/.*>\(ieel-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/')
set -x
IEEL_FROM_VER="${IEEL_FROM_ARCHIVE#*-}"
IEEL_FROM_VER="${IEEL_FROM_VER%.tar.gz}"
set +x
echo "+ curl -k -O -u \"${JENKINS_USER}:***********\" \"${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/arch=x86_64,distro=$JENKINS_DISTRO/artifact/chroma-bundles/$IEEL_FROM_ARCHIVE\""
curl -k -O -u "${JENKINS_USER}:${JENKINS_PULL}" "${JENKINS_URL}job/$BUILD_JOB/$BUILD_NUM/arch=x86_64,distro=$JENKINS_DISTRO/artifact/chroma-bundles/$IEEL_FROM_ARCHIVE"
set -x

# Install and setup old manager
scp $IEEL_FROM_ARCHIVE $CHROMA_DIR/chroma-manager/tests/utils/install.exp root@$CHROMA_MANAGER:/tmp
ssh root@$CHROMA_MANAGER "#don't do this, it hangs the ssh up, when used with expect, for some reason: exec 2>&1
set -ex
yum -y install expect

# Unpack the previous install into /tmp/$PREVIOUS_INSTALL_DIR
cd /tmp
mkdir $PREVIOUS_INSTALL_DIR
mv $IEEL_FROM_ARCHIVE $PREVIOUS_INSTALL_DIR/$IEEL_FROM_ARCHIVE
mv install.exp $PREVIOUS_INSTALL_DIR/install.exp

cd $PREVIOUS_INSTALL_DIR
tar xzvf $IEEL_FROM_ARCHIVE

# Install from the installation package
cd ${IEEL_FROM_ARCHIVE%%.tar.gz}
# hack out the O/S version check in old version so it installs on the new O/S
ed <<"EOF" install
/_check_platform()\$/d
wq
EOF
if ! expect ../install.exp $CHROMA_USER $CHROMA_EMAIL $CHROMA_PASS ${CHROMA_NTP_SERVER:-localhost}; then
    rc=\${PIPESTATUS[0]}
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit \$rc
fi
rpm -qa | sort > /tmp/rpms_before_upgrade"
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

# Install and setup chroma software storage appliances
pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]}) "exec 2>&1; set -xe
# if this node uses the Intel proxies, make sure the agent is doing so
if [ -f /etc/profile.d/intel_proxy.sh ]; then
    echo \". /etc/profile.d/intel_proxy.sh\" > /etc/sysconfig/chroma-agent
    # IEEL prior to 3.0.0.0 can't set proxies in the chroma-agent environment
    # so we have to hack that into the repos for (real) RHEL
    if [ ${IEEL_FROM_VER//./} -lt 3000 -a -f /etc/yum.repos.d/redhat.repo ]; then
        proxy=\$(sed -ne '/^export http_proxy=/s/.*\"\(.*\)\"\$/\1/p' /etc/profile.d/intel_proxy.sh)
        # this doesn't actually work due to RHBZ#1315693
        #subscription-manager repos | sed -n -e 's/^Repo ID:  *//p' | xargs -i -n 1 subscription-manager repo-override --proxy=\$proxy --add=proxy:\$proxy --repo={}
        # temporary hack until RH can fix their SM bugs
        # do a global yum.conf proxy configuration and disable local repos
        ed /etc/yum.conf << EOF
/^$/i
proxy=\$proxy
.
wq
EOF
        sed -i -e \"/^\(\[.*\)\$/s//\1\\\\
proxy=_none_/\" /etc/yum.repos.d/cobbler-config.repo
    fi
fi" | dshbak -c

# Install a client
source $CHROMA_DIR/chroma-manager/tests/framework/integration/utils/enable_kernels_repo.sh ${WORKERS[@]} $CLIENT_1
if [ ${IEEL_FROM_VER//./} -lt 3000 ]; then
    OLD_CLIENT=true
fi
source $CHROMA_DIR/chroma-manager/tests/framework/integration/utils/install_client.sh

echo "Create and exercise a filesystem..."

TESTS="$TESTS_DIR/../shared_storage_configuration/test_cluster_setup.py \
       $TESTS_DIR/test_create_filesystem.py:TestCreateFilesystem.test_create"

ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x ~/test_report_pre_upgrade.xml $TESTS"

echo "Now upgrade IML..."

# Install and setup manager
scp $ARCHIVE_NAME $CHROMA_DIR/chroma-manager/tests/utils/upgrade.exp root@$CHROMA_MANAGER:/tmp
ssh root@$CHROMA_MANAGER "#don't do this, it hangs the ssh up, when used with expect, for some reason: exec 2>&1
set -ex
existing_IML_version=\$(rpm -q --qf \"%{VERSION}-%{RELEASE}\n\" chroma-manager)
yum -y update

# Unpack the previous install into /tmp/$UPGRADE_INSTALL_DIR
cd /tmp
mkdir $UPGRADE_INSTALL_DIR
mv $ARCHIVE_NAME $UPGRADE_INSTALL_DIR/$ARCHIVE_NAME
mv upgrade.exp $UPGRADE_INSTALL_DIR/upgrade.exp

cd $UPGRADE_INSTALL_DIR
tar xzvf $ARCHIVE_NAME
cd $(basename $ARCHIVE_NAME -current.tar.gz)

# Install from the installation package
echo \"First without access to YUM repos\"

ips=\$(grep -e ^base -e ^mirror /etc/yum.repos.d/* | sed -e 's/.*:\/\/\([^/]*\)\/.*/\1/g' -e 's/:.*//' | sort -u | while read n; do getent ahosts \$n | sed -ne 's/\(.*\)  STREAM .*/\1/p'; done | sort -u)
for ip in \$ips; do
    iptables -I OUTPUT -d \$ip -p tcp --dport 80 -j REJECT
done
iptables -L -nv

if expect ../upgrade.exp; then
    echo \"Installation unexpectedly succeeded without access to repos\"
    for ip in \$ips; do
        iptables -D OUTPUT -d \$ip -p tcp --dport 80 -j REJECT
    done
    exit 1
fi
for ip in \$ips; do
    if ! iptables -D OUTPUT -d \$ip -p tcp --dport 80 -j REJECT; then
        rc=\${PIPESTATUS[0]}
        iptables -L -nv
        exit \$rc
    fi
done

echo \"Now with EPEL configured\"

cat <<EOF > /etc/yum.repos.d/epel.repo
[epel]
name=epel
baseurl=http://${COBBLER_SERVER:-10.14.80.10}/cobbler/repo_mirror/addon-epel\$(rpm --eval %rhel)-x86_64/
enabled=1
priority=1
gpgcheck=0
sslverify=0
EOF
yum makecache

if expect ../upgrade.exp; then
    echo \"Installation unexpectedly succeeded with EPEL configured\"
    rm -f /etc/yum.repos.d/epel.repo
    exit 1
fi
rm -f /etc/yum.repos.d/epel.repo

if $RHEL; then
    release=\$(lsb_release -sr || sed -n -e '1s/.* release \(.*\) .*/\1/p' /etc/issue)
    yum-config-manager --disable  rhel-\$(rpm --eval %rhel)-server-optional-rpms,RHEL-\$release-optional-x86_64
    # let's also remove any local RH optional repo
    if grep \"RHEL-\$(rpm --eval %rhel)\.[0-9]-optional-x86_64\" /etc/yum.repos.d/cobbler-config.repo; then
        ed <<\"EOF\" /etc/yum.repos.d/cobbler-config.repo
/\[RHEL-\$(rpm --eval %rhel)\.[0-9]-optional-x86_64\]/;/^$/d
wq
EOF
    fi
fi

if ! expect ../upgrade.exp; then
    rc=\${PIPESTATUS[0]}
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit \$rc
fi
# make sure it really did do an upgrade
upgraded_IML_version=\$(rpm -q --qf \"%{VERSION}-%{RELEASE}\n\" chroma-manager)
if [ \$existing_IML_version = \$upgraded_IML_version ]; then
    echo \"Upgrade didn't actually upgrade the chroma-manager package\"
    echo \"Install log:\"
    cat /var/log/chroma/install.log
    exit 1
fi
# install cman here to test that the fence-agents-iml package is being a
# "duck-like" replacement for fence-agents since cman depends on
# fence-agents
yum -y install cman

cat <<\"EOF1\" > /usr/share/chroma-manager/local_settings.py
import logging
LOG_LEVEL = logging.DEBUG
$LOCAL_SETTINGS
EOF1

# Ensure that coverage is disabled
# https://github.com/pypa/virtualenv/issues/355
python_version=\$(python -c 'import platform; print \".\".join(platform.python_version_tuple()[0:2])')
rm -f /usr/lib/python\$python_version/site-packages/sitecustomize.py*"

echo "End upgrade and setup."

echo "Test existing filesystem is still there"

TESTS="$TESTS_DIR/test_data_consistancy.py \
       $TESTS_DIR/test_update_with_yum.py:TestYumUpdate.test_no_retired_repos \
       $TESTS_DIR/test_update_with_yum.py:TestYumUpdate.test_yum_update \
       $TESTS_DIR/test_create_filesystem.py:TestExistsFilesystem.test_exists"

ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x ~/test_report_post_upgrade.xml $TESTS"

# now provide an information inventory of the difference in the RPM
# catalog after the upgrade

pdsh -l root -R ssh -S -w $(spacelist_to_commalist $ALL_NODES) "exec 2>&1; set -xe
if [ -f /tmp/rpms_before_upgrade ]; then
    diff -u /tmp/rpms_before_upgrade <(rpm -qa | sort)
    rm /tmp/rpms_before_upgrade
fi" | dshbak -c

# test that removing the chroma-manager RPM removes /var/lib/chroma
ssh root@$CHROMA_MANAGER "set -xe
exec 2>&1
ls -l /var/lib/chroma
rpm -e chroma-manager-cli chroma-manager chroma-manager-libs
if [ -d /var/lib/chroma ]; then
    echo \"Removing RPMs failed to clean up /var/lib/chroma\"
    ls -l /var/lib/chroma
    exit 1
fi"

exit 0
