#!/bin/bash -ex

make substs
. tests/framework/utils/defaults.sh
. tests/framework/utils/selective_auto_pass.sh
. tests/framework/utils/cleanup.sh

set_defaults true
check_for_autopass


CHROMA_DIR="$PWD"

export CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:-"$CHROMA_DIR/tests/framework/integration/shared_storage_configuration/full_cluster/shared_storage_configuration_cluster_cfg.json"}

CURRENT_IML_VERSION=$(make -s -f include/Makefile.version .ieel_version) || true


# Gather logs from nodes and release the cluster at exit
trap "set +e; cleanup" EXIT

$CHROMA_DIR/tests/framework/utils/provisioner_interface/provision_cluster

eval $(python $CHROMA_DIR/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

RHEL=false
if [[ $slave =~ rhel[0-9]+&&.* ]]; then
    RHEL=true
fi
export RHEL

echo "Beginning automated test run..."
$CHROMA_DIR/tests/framework/integration/installation_and_upgrade/cluster_setup
$CHROMA_DIR/tests/framework/integration/installation_and_upgrade/run_tests
echo "Automated test run complete."
