SRC_REPO = http://nginx.org/packages/centos/6/x86_64/RPMS/

ALL_RPMS = nginx-1.6.2-1.el6.ngx.x86_64.rpm
NO_REQUIREMENT = nginx

rpm_file:
	@echo $(ALL_RPMS)

include ../include/Makefile.fetch-from-repo
