LOCATION := http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/16/Everything/source/SRPMS/python-dateutil-1.5-3.fc16.src.rpm
REQUIREMENT := python-dateutil

include ../include/Makefile.rpm
