#!/bin/bash -ex

. chroma-manager/tests/framework/utils/defaults.sh
. chroma-manager/tests/framework/utils/selective_auto_pass.sh

set_defaults true
check_for_autopass

export CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:-"$CHROMA_DIR/chroma-manager/tests/framework/integration/shared_storage_configuration/full_cluster/shared_storage_configuration_cluster_cfg.json"}
CURRENT_IEEL_VERSION=$(make -f include/Makefile.version .ieel_version 2>/dev/null) || true
SLAVE=${slave:?"Need to set slave"}

cd $WORKSPACE

set +x  # DONT REMOVE/COMMENT or you will risk exposing the jenkins-pull api token in the console logs.
echo "+ curl -f -k -o $SHORT_ARCHIVE_NAME-$CURRENT_IEEL_VERSION-current.tar.gz -u $JENKINS_USER:********* \"$JOB_URL/$SHORT_ARCHIVE_NAME-$CURRENT_IEEL_VERSION.tar.gz\""
curl -f -k -o $SHORT_ARCHIVE_NAME-$CURRENT_IEEL_VERSION-current.tar.gz -u $JENKINS_USER:$JENKINS_PULL "$JOB_URL/$SHORT_ARCHIVE_NAME-$CURRENT_IEEL_VERSION.tar.gz"
set -x

# Gather logs from nodes and release the cluster at exit
trap "set +e
export PYTHONPATH=chroma/chroma-common:$PYTHONPATH
python \"$CHROMA_DIR\"/chroma-manager/tests/integration/utils/chroma_log_collector.py \"$WORKSPACE/test_logs\" $CLUSTER_CONFIG || true
\"$CHROMA_DIR\"/chroma-manager/tests/framework/utils/provisioner_interface/release_cluster" EXIT

$CHROMA_DIR/chroma-manager/tests/framework/utils/provisioner_interface/provision_cluster

# see if this cures the 401 errors from jenkins
eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")
ssh root@$TEST_RUNNER "exec 2>&1; set -e; set +x
sed -i -e 's/Aitahd9u/"$JENKINS_PULL"/g' /etc/yum.repos.d/autotest.repo"

# see if this mitigates the near constant failure to complete a yum upgrade from the RH CDN
pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]} ${WORKERS[@]}) "exec 2>&1; set -xe
cat <<\"EOF\" >> /etc/yum.conf
retries=100
timeout=300
EOF" | dshbak -c

echo "Beginning automated test run..."
set +x
export JENKINS_PULL
set -x
$CHROMA_DIR/chroma-manager/tests/framework/integration/installation_and_upgrade/cluster_setup
$CHROMA_DIR/chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
echo "Automated test run complete."
