RPM_NAME := chroma-repo
TARGET :=
REQUIREMENT :=

download:
	@echo "Nothing to download"

cleanrepo:
	rm -rf $(REPO)

.PHONY: download

include ../include/Makefile.rpmbuild
include ../include/Makefile.install
