NAME		:= request
VERSION		:= 2.33.0
SHA1SUM		:= 5167878131726070ec633752ea230a2379dc65ff
DEPENDENCIES	:= qs http-signature node-uuid json-stringify-safe tunnel-agent form-data oauth-sign tough-cookie mime aws-sign2 hawk forever-agent

include ../include/Makefile.rpm-from-npm
