NAME		:= request
VERSION		:= 2.27.0
SHA1SUM		:= dfb1a224dd3a5a9bade4337012503d710e538668
DEPENDENCIES	:= qs aws-sign http-signature cookie-jar node-uuid json-stringify-safe tunnel-agent form-data oauth-sign mime hawk forever-agent

include ../include/Makefile.rpm-from-npm
