NAME		:= request
VERSION		:= 2.29.0
SHA1SUM		:= 0d4b8de70d26a9911a8344af9a0e8edab81ff1c3
DEPENDENCIES	:= qs http-signature node-uuid json-stringify-safe tunnel-agent form-data oauth-sign tough-cookie mime aws-sign2 hawk forever-agent

include ../include/Makefile.rpm-from-npm
