SRC_REPO = https://kojipkgs.fedoraproject.org//packages/dkms/2.2.0.3/28.git.7c3e7c5.el6/noarch/

ALL_RPMS = dkms-2.2.0.3-28.git.7c3e7c5.el6.noarch.rpm
NO_REQUIREMENT = dkms

include ../include/Makefile.fetch-from-repo
