SRC_REPO = https://kojipkgs.fedoraproject.org/packages/dkms/2.3/1.20161202gitde1dca9.el6/noarch/

ALL_RPMS = dkms-2.3-1.20161202gitde1dca9.el6.noarch.rpm
NO_REQUIREMENT = dkms

include ../include/Makefile.fetch-from-repo
