#!/bin/bash

SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
if ! grep -qs "^$SOB" "$1"; then
    mv "$1"{,.tmp}
    trap 'rm $1.tmp' EXIT
    added=false
    while read -r line; do
        if ! $added && [[ $line == \#* ]]; then
            echo -e "\n$SOB"
            added=true
        fi
        echo "$line"
    done < "$1".tmp > "$1"
    if ! $added; then
        echo -e "\n$SOB" >> "$1"
    fi
fi
