include $(CURDIR)/../../include/Makefile.version
RPMS            := chroma-manager
DESC            := $(PRODUCT_NAME)
NAME		:= $(SHORT_PRODUCT_NAME)
VERSION		:= $(PACKAGE_VERSION)
BUNDLE_NAME     := $(NAME)-manager-$(VERSION)

include ../include/Makefile.bundle
