include $(CURDIR)/../../include/Makefile.version
RPMS        := chroma-manager
DESC        := $(PRODUCT_NAME)
NAME		:= $(SHORT_PRODUCT_NAME)-$(PACKAGE_VERSION)
BUNDLE_NAME := $(NAME)-manager

include ../include/Makefile.bundle
