#!/bin/bash

set -e

# shellcheck disable=SC1091
. jenkins_account

# (much of this needs to be extraced into a per-user config file:)
# for a remote dev cluster:
#HOST=lotus-31
#CLUSTER=""
#CLUSTER="1"
# empty $HOST for a local Vagrant cluster:
HOST=${HOST:-""}
CLUSTER=${CLUSTER:-""}
CHROMA_MANAGER="${HOST}vm${CLUSTER}3"
# shellcheck disable=SC2034
STORAGE_NODES="${HOST}vm${CLUSTER}[5-8]"
ALL_NODES="${HOST}vm${CLUSTER}[2-9]"
EE_VERSION=$(make -s -f include/Makefile.version .ieel_version)
# if you want a release from jenkins:
#EE_JOB_NUM=292
# otherwise:
ARCHIVE_NAME="iml-$EE_VERSION.tar.gz"

CHROMA_DIR=.
CHROMA_USER="admin"
CHROMA_EMAIL="iml@whamcloud.com"
CHROMA_PASS="lustre"
CHROMA_NTP_SERVER="localhost"
pdsh -R ssh -l root -S -w "$ALL_NODES" "set -ex
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/managerforlustre/manager-for-lustre/repo/epel-7/managerforlustre-manager-for-lustre-epel-7.repo
yum-config-manager --add-repo http://mirror.centos.org/centos/7/extras/x86_64/
yum -y install epel-release
# alternative repos for lustre-master
#yum-config-manager --add-repo https://build.whamcloud.com/job/lustre-master/lastSuccessfulBuild/arch=x86_64,build_type=server,distro=el7,ib_stack=inkernel/artifact/artifacts/
##sed -i -e '1d' -e '2s/^.*$/[lustre]/' -e '/baseurl/s/,/%2C/g' -e '/enabled/a gpgcheck=0' /etc/yum.repos.d/build.whamcloud.com_job_lustre-master_lastSuccessfulBuild_arch\=x86_64\,build_type\=server\,distro\=el7\,ib_stack\=inkernel_artifact_artifacts_.repo
#sed -i -e '2s/^.*$/[lustre]/' -e '/baseurl/s/,/%2C/g' -e '/enabled/a gpgcheck=0' /etc/yum.repos.d/build.whamcloud.com_job_lustre-master_lastSuccessfulBuild_arch\=x86_64\,build_type\=server\,distro\=el7\,ib_stack\=inkernel_artifact_artifacts_.repo
#yum-config-manager --add-repo https://build.whamcloud.com/job/e2fsprogs-master/arch=x86_64,distro=el7/lastSuccessfulBuild/artifact/_topdir/RPMS/
##sed -i -e '1d' -e '2s/^.*$/[e2fsprogs]/' -e '/baseurl/s/,/%2C/g' -e '/enabled/a gpgcheck=0' /etc/yum.repos.d/build.whamcloud.com_job_e2fsprogs-master_arch\=x86_64\,distro\=el7_lastSuccessfulBuild_artifact__topdir_RPMS_.repo
#sed -i -e '2s/^.*$/[e2fsprogs]/' -e '/baseurl/s/,/%2C/g' -e '/enabled/a gpgcheck=0' /etc/yum.repos.d/build.whamcloud.com_job_e2fsprogs-master_arch\=x86_64\,distro\=el7_lastSuccessfulBuild_artifact__topdir_RPMS_.repo
#yum -y install distribution-gpg-keys-copr
#if ! ls /usr/share/distribution-gpg-keys/copr/copr-*manager-for-lustre*; then
#    rpm --import https://copr-be.cloud.fedoraproject.org/results/managerforlustre/manager-for-lustre/pubkey.gpg
#fi
yum -y install strace vim-enhanced" | dshbak -c
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi

if [ -n "$ARCHIVE_NAME" ]; then
    SCP_FILES="chroma-bundles/$ARCHIVE_NAME"
fi
# shellcheck disable=SC2086
# shellcheck disable=SC2029
scp $SCP_FILES "$CHROMA_DIR"/chroma-manager/tests/utils/install.exp root@"$CHROMA_MANAGER":/tmp
ssh -t root@"$CHROMA_MANAGER" "set -ex
yum -y install expect
cd /tmp
if [ -f \"$ARCHIVE_NAME\" ]; then
    tar xzvf \"$ARCHIVE_NAME\"
    cd iml-$EE_VERSION
elif [ ! -d iml-$EE_VERSION-$EE_JOB_NUM ]; then
    if [ ! -f iml-$EE_VERSION-$EE_JOB_NUM.tar.gz ] || ! tar tzvf iml-$EE_VERSION-$EE_JOB_NUM.tar.gz; then
        curl -u $JENKINS_USER:$JENKINS_PASSWORD -v -o iml-$EE_VERSION-$EE_JOB_NUM.tar.gz 'http://jenkins.lotus.hpdd.lab.intel.com/job/ieel/$EE_JOB_NUM/artifact/iml-$EE_VERSION.tar.gz'
    fi
    tar xzvf iml-$EE_VERSION-$EE_JOB_NUM.tar.gz
    mv iml-$EE_VERSION{,-$EE_JOB_NUM}
    cd iml-$EE_VERSION-$EE_JOB_NUM
fi
if ! expect ../install.exp $CHROMA_USER $CHROMA_EMAIL $CHROMA_PASS ${CHROMA_NTP_SERVER:-localhost}; then
    cat /var/log/chroma/install.log
    exit 1
fi

echo \"Installation complete.  Manager can be reached at https://\$(ip addr ls dev eth0 | grep -Po 'inet \K[\d.]+')/\"
"
