#!/bin/bash

HAS_ISSUES=0
FIRST_FILE=1

for file in $(git diff --name-only --staged); do
    FMT_RESULT=""
    if [ ! -e $file ]; then
	continue
    fi
    case "$file" in
	*.rs) FMT_RESULT="$(rustfmt --edition 2018 --check $file 2>/dev/null || true)" ;;
	*.py) if ! black -q --check $file; then FMT_RESULT="need blackening"; fi ;;
    esac

    if [ "$FMT_RESULT" != "" ]; then
        if [ $FIRST_FILE -eq 0 ]; then
            echo -n ", "
        fi
        echo -n "$file"
        HAS_ISSUES=1
        FIRST_FILE=0
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo -e ".\nYour code has formatting issues in files listed above. Format your code!"
exit 1
