#!/usr/bin/env python

#http://tech.yipit.com/2011/11/16/183772396/

import os
import re
import subprocess
from distutils import spawn
from functools import partial
import sys

modified = re.compile('^(?:M|A)(\s+)(?P<name>.*)')

DISABLED_CHECKS = [
    {
        'output': 'Checking for pdbs...',
        'command': 'grep -n "import pdb" %s',
        'ignore_files': ['.*pre-commit'],
        'print_filename': True,
    },
    {
        'output': 'Checking for ipdbs...',
        'command': 'grep -n "import ipdb" %s',
        'ignore_files': ['.*pre-commit'],
        'print_filename': True,
    },
    {
        'output': 'Checking for print statements...',
        'command': 'grep -n print %s',
        'match_files': ['.*\.py$'],
        'ignore_files': ['.*migrations.*', '.*management/commands.*', '.*manage.py', '.*/scripts/.*'],
        'print_filename': True,
    },
    {
        'output': 'Checking for console.log()...',
        'command': 'grep -n console.log %s',
        'match_files': ['.*yipit/.*\.js$'],
        'print_filename': True,
    },
    {
        'output': 'Checking for debugger...',
        'command': 'grep -n debugger %s',
        'match_files': ['.*\.js$'],
        'print_filename': True,
    },
    {
        'output': 'Checking for Sass changes...',
        'command': 'sass --quiet --update %s',
        'match_files': ['.*\.scss$'],
        'print_filename': True,
    },
]
CHECKS = [
    {
        'output': 'Running Pyflakes...',
        'command': 'pyflakes %s',
        'match_files': [
            '.*\.py$',
            '.*setup.py.in'            ],
        # NB excluding chroma_core/models/__init__.py because imports things
        # but don't use them
        'ignore_files': ['.*settings/.*',
            '.*manage.py',
            '.*migrations.*',
            '.*/terrain/.*',
            '.*chroma_core/models/__init__.py',
            '.*chroma_core/lib/storage_plugin/api/__init__.py',
            '.*chroma_core/management/__init__.py',
            '.*settings.py',
            '.*example_storage_plugin_package/example_storage_plugin/__init__.py',
            '.*chroma-manager/tests/unit/chroma_core/lib/storage_plugin/junk.py',
            '.*/chroma-manager/docs/.*/conf.py$',
            '.*/features/steps/.*\.py',
            '.*/BUILD/.*',
            '.*/chroma-externals/.*'
            ],
        'print_filename': False,
    },
    {
        'output': 'Running pep8...',
        'command': 'pep8 -r --ignore=E501,E251,E711,E712 %s',
        'match_files': ['.*\.py$', '.*setup.py.in'],
        'ignore_files': [
            '.*migrations.*',
            '.*manage.py',
            '.*/BUILD/.*',
            '.*/chroma-externals/.*',
        ],
        'print_filename': False
    },
    {
        'output': 'Checking boilerplate...',
        'command': 'scripts/boilerplate.py test %s',
        'match_files': [
            '.*\.py$',
            '.*chroma_ui/static/js/.*\.js$'
        ],
        'ignore_files': [
            '.*/chroma-manager/r3d/prettytable.py',
            '.*scm_version.py$',
            '.*/chroma-manager/docs/conf.py',
            '.*/chroma-manager/userdocs/conf.py',
            '.*/chroma-manager/docs/lib/tastydoc.py',
            '.*/chroma-manager/polymorphic/.*',
            '.*/chroma-manager/.*migrations.*',
            '.*/tests/.*.py',
            '.*/manage.py',
            '.*/BUILD/.*',
            '.*chroma_ui/static/js/lib/.*\.js$',
            '.*/chroma-externals/.*',
        ],
        'print_filename': True
    }
]

DJANGO_PROJECTS = ['chroma-manager']

local_node_modules_dir = 'chroma-manager/chroma_ui_new/gulp/node_modules'

jshint_bin_dir = local_node_modules_dir + '/gulp-jshint/node_modules/jshint/bin'

JS_QUALITY_FILES = {
    'match_files': [
        '.*/chroma_ui/static/js/.+/[^/]+\.js$',
        '.*/chroma_ui/test/spec/.+/[^/]+\.js$',
        '.*/chroma_ui/static/js/app.js$',
        '.*/chroma_ui/static/js/constants.js$',
        '.*/ui-modules/.*\.js$'
    ],
    'ignore_files': [
        '.*/chroma_ui/static/js/lib/.*',
        '.*/chroma_ui_new/source/chroma_ui/bower_components/.*',
        '.*/chroma_ui_new/source/chroma_ui/vendor/.*',
        '.*/chroma_ui_new/karma.*\.conf\.js',
        '.*/chroma_ui_new/test/matchers/matchers\.js',
        '.*/chroma-manager/chroma_ui_new/node_modules/.*',
        '.*/chroma-manager/chroma_ui_new/gulp/node_modules/.*',
        '.*/chroma-manager/chroma_ui_new/test/data-fixtures/.*'
    ]

}

JS_HINT_CHECK = {
        'output': 'Running JSHint...',
        'command': jshint_bin_dir + '/jshint %s',
        'print_filename': True,
    }
JS_HINT_CHECK.update(JS_QUALITY_FILES)

jscs_bin_dir = local_node_modules_dir + '/gulp-jscs/node_modules/jscs/bin'

jscs_command = '%s/%s/jscs' % (os.path.dirname(os.path.dirname(os.path.realpath(__file__))), jscs_bin_dir)

JS_CS_CHECK = {
        'output': 'Running JSCS...',
        'command': jscs_command + ' %s -r inline',
        'print_filename': False,
        'use_dirname_cwd': True
    }
JS_CS_CHECK.update(JS_QUALITY_FILES)

has_js_hint = spawn.find_executable('jshint', path=jshint_bin_dir)

has_js_cs = spawn.find_executable('jscs', path=jscs_bin_dir)

has_node_js = spawn.find_executable('node')

(CHECKS if has_js_hint and has_node_js else DISABLED_CHECKS).append(JS_HINT_CHECK)

(CHECKS if has_js_cs and has_node_js else DISABLED_CHECKS).append(JS_CS_CHECK)

if not has_js_hint:
    print "WARNING: skipping JSHint check"

if not has_js_cs:
    print "WARNING: skipping JSCS check"

if not has_node_js:
    print "WARNING: skipping SEMVER check"

def matches_file(file_name, match_files):
    return any(re.compile(match_file).match(file_name) for match_file in match_files)

def check_files(files, check):
    result = 0
    print check['output']
    for file_name in files:
        if not 'match_files' in check or matches_file(file_name, check['match_files']):
            if not 'ignore_files' in check or not matches_file(file_name, check['ignore_files']):
                popen = partial(subprocess.Popen, check['command'] % file_name,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

                if check.get('use_dirname_cwd', None):
                    process = popen(cwd=os.path.dirname(file_name))
                else:
                    process = popen()
                out, err = process.communicate()
                if out or err:
                    if check['print_filename']:
                        prefix = '\t%s:' % file_name
                    else:
                        prefix = '\t'
                    output_lines = ['%s%s' % (prefix, line) for line in out.splitlines()]

                    print '\n'.join(output_lines)

                    if err:
                        print err
                    result = 1
    return result

def main(all_files, exclude = []):
    files = []
    if all_files:
        for root, dirs, file_names in os.walk('.'):
            for ex in exclude:
                if ex in dirs:
                    dirs.remove(ex)
            for file_name in file_names:
                files.append(os.path.join(root, file_name))
    else:
        p = subprocess.Popen(['git', 'rev-parse', '--show-toplevel'], stdout=subprocess.PIPE)
        out, err = p.communicate()
        rc = p.wait()
        if rc != 0:
            raise RuntimeError("Cannot invoke git %s" % out)
        git_root = out.strip()

        p = subprocess.Popen(['git', 'status', '--porcelain'], stdout=subprocess.PIPE)
        out, err = p.communicate()
        for line in out.splitlines():
            match = modified.match(line)
            if match:
                files.append(os.path.join(git_root, match.group('name')))

                if match.group('name') == 'chroma-externals':
                    print "WARNING:\n"\
                          "WARNING: This patch modifies the chroma-externals reference are you sure this is intended\n"\
                          "WARNING:"
    result = 0

    for project_dir in DJANGO_PROJECTS:
        project_dir = os.path.join(os.getcwd(), project_dir)
        manage_script = os.path.join(project_dir, 'manage.py')
        p = subprocess.Popen(['python', manage_script, '--version'], stdout=subprocess.PIPE, cwd = project_dir)
        out, err = p.communicate()
        if p.returncode == 0:
            print 'Running Django Code Validator...'
            return_code = subprocess.call(['python', manage_script, 'validate'], cwd = project_dir)
            result = return_code or result
        else:
            print "WARNING: skipping Django model validation"

    for check in CHECKS:
        result = check_files(files, check) or result

    sys.exit(result)

# python 2.4 doesn't have any()
try:
    any
except NameError:
    def any(iterable):
        for element in iterable:
            if element:
                return True
        return False


if __name__ == '__main__':
    all_files = False
    exclude = ['.git']
    n = 1
    while n < len(sys.argv):
        if sys.argv[n] == '--all-files':
            all_files = True
        elif sys.argv[n] == '--exclude':
            exclude.append(sys.argv[n + 1])
            n = n + 1
        n = n + 1

    print "exclude %s" % exclude
    main(all_files, exclude)
