#!/usr/bin/env python

#http://tech.yipit.com/2011/11/16/183772396/

import os
import re
import subprocess
import sys

modified = re.compile('^(?:M|A)(\s+)(?P<name>.*)')

DISABLED_CHECKS = [
    {
        'output': 'Checking for pdbs...',
        'command': 'grep -n "import pdb" %s',
        'ignore_files': ['.*pre-commit'],
        'print_filename': True,
    },
    {
        'output': 'Checking for ipdbs...',
        'command': 'grep -n "import ipdb" %s',
        'ignore_files': ['.*pre-commit'],
        'print_filename': True,
    },
    {
        'output': 'Checking for print statements...',
        'command': 'grep -n print %s',
        'match_files': ['.*\.py$'],
        'ignore_files': ['.*migrations.*', '.*management/commands.*', '.*manage.py', '.*/scripts/.*'],
        'print_filename': True,
    },
    {
        'output': 'Checking for console.log()...',
        'command': 'grep -n console.log %s',
        'match_files': ['.*yipit/.*\.js$'],
        'print_filename': True,
    },
    {
        'output': 'Checking for debugger...',
        'command': 'grep -n debugger %s',
        'match_files': ['.*\.js$'],
        'print_filename': True,
    },
    {
       'output': 'Running Jshint...',
       # By default, jshint prints 'Lint Free!' upon success. We want to filter this out.
       'command': 'jshint %s | grep -v "Lint Free!"',
       'match_files': ['.*yipit/.*\.js$'],
       'print_filename': False,
    },
    {
        'output': 'Checking for Sass changes...',
        'command': 'sass --quiet --update %s',
        'match_files': ['.*\.scss$'],
        'print_filename': True,
    },
]
CHECKS = [
    {
        'output': 'Running Pyflakes...',
        'command': 'pyflakes %s',
        'match_files': [
            '.*\.py$',
            '.*setup.py.in'            ],
        # NB excluding chroma_core/models/__init__.py because imports things
        # but don't use them
        'ignore_files': ['.*settings/.*',
            '.*manage.py',
            '.*migrations.*',
            '.*/terrain/.*',
            '.*chroma_core/models/__init__.py',
            '.*chroma_core/lib/storage_plugin/api/__init__.py',
            '.*settings.py',
            '.*example_storage_plugin_package/example_storage_plugin/__init__.py',
            '.*/chroma-director/.*'],
        'print_filename': False,
    },
    {
        'output': 'Running pep8...',
        'command': 'pep8 -r --ignore=E501,E251 %s',
        'match_files': ['.*\.py$', '.*setup.py.in'],
        'ignore_files': ['.*migrations.*', '.*manage.py', '.*/chroma-director/.*'],
        'print_filename': False,
    },
    {
        'output': 'Checking boilerplate...',
        'command': 'scripts/boilerplate.py test %s',
        'match_files': [
            '.*\.py$',
            '.*chroma_ui/static/js/[^/]+\.js$'
        ],
        'ignore_files': [
            '.*/chroma-manager/docs/conf.py',
            '.*/chroma-manager/userdocs/conf.py',
            '.*/chroma-manager/docs/lib/tastydoc.py',
            '.*/chroma-manager/polymorphic/.*',
            '.*/chroma-manager/.*migrations.*',
            '.*/tests/.*.py',
            '.*/manage.py',
            '.*/chroma-director/.*'],
        'print_filename': True
    }
]

DJANGO_PROJECTS = ['chroma-manager']


def matches_file(file_name, match_files):
    return any(re.compile(match_file).match(file_name) for match_file in match_files)


def check_files(files, check):
    result = 0
    print check['output']
    for file_name in files:
        if not 'match_files' in check or matches_file(file_name, check['match_files']):
            if not 'ignore_files' in check or not matches_file(file_name, check['ignore_files']):
                process = subprocess.Popen(check['command'] % file_name, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
                out, err = process.communicate()
                if out or err:
                    if check['print_filename']:
                        prefix = '\t%s:' % file_name
                    else:
                        prefix = '\t'
                    output_lines = ['%s%s' % (prefix, line) for line in out.splitlines()]
                    print '\n'.join(output_lines)
                    if err:
                        print err
                    result = 1
    return result


def main(all_files, exclude = []):
    files = []
    if all_files:
        for root, dirs, file_names in os.walk('.'):
            for ex in exclude:
                if ex in dirs:
                    dirs.remove(ex)
            for file_name in file_names:
                files.append(os.path.join(root, file_name))
    else:
        p = subprocess.Popen(['git', 'rev-parse', '--show-toplevel'], stdout=subprocess.PIPE)
        out, err = p.communicate()
        rc = p.wait()
        if rc != 0:
            raise RuntimeError("Cannot invoke git %s" % out)
        git_root = out.strip()

        p = subprocess.Popen(['git', 'status', '--porcelain'], stdout=subprocess.PIPE)
        out, err = p.communicate()
        for line in out.splitlines():
            match = modified.match(line)
            if match:
                files.append(os.path.join(git_root, match.group('name')))
    
    result = 0
    
    for project_dir in DJANGO_PROJECTS:
        project_dir = os.path.join(os.getcwd(), project_dir)
        manage_script = os.path.join(project_dir, 'manage.py')
        p = subprocess.Popen(['python', manage_script, '--version'], stdout=subprocess.PIPE, cwd = project_dir)
        out, err = p.communicate()
        if p.returncode == 0:
            print 'Running Django Code Validator...'
            return_code = subprocess.call(['python', manage_script, 'validate'], cwd = project_dir)
            result = return_code or result
        else:
            print "WARNING: skipping Django model validation"
    
    for check in CHECKS:
        result = check_files(files, check) or result
    
    sys.exit(result)

# python 2.4 doesn't have any()
try:
    any
except NameError:
    def any(iterable):
        for element in iterable:
            if element:
                return True
        return False


if __name__ == '__main__':
    all_files = False
    exclude = ['.git']
    n = 1
    while n < len(sys.argv):
        if sys.argv[n] == '--all-files':
            all_files = True
        elif sys.argv[n] == '--exclude':
            exclude.append(sys.argv[n + 1])
            n = n + 1
        n = n + 1

    print "exclude %s" % exclude
    main(all_files, exclude)
