#! /bin/sh
echo "Creating $INFLUXDB_IML_DB, $INFLUXDB_STRATAGEM_SCAN_DB and $INFLUXDB_IML_STATS_DB databases."
while ! influx -execute "CREATE DATABASE $INFLUXDB_IML_DB" >/dev/null; do
    echo "influx not yet ready"
    sleep 1
done

influx -execute "CREATE DATABASE $INFLUXDB_STRATAGEM_SCAN_DB"
influx -execute "ALTER RETENTION POLICY \"autogen\" ON \"$INFLUXDB_STRATAGEM_SCAN_DB\" DURATION 90d SHARD DURATION 9d"
influx -execute "CREATE DATABASE $INFLUXDB_IML_STATS_DB"
influx -execute "CREATE RETENTION POLICY \"long_term\" ON \"$INFLUXDB_IML_STATS_DB\" DURATION $INFLUXDB_IML_STATS_LONG_DURATION REPLICATION 1 SHARD DURATION 5d" -database $INFLUXDB_IML_STATS_DB
influx -execute "CREATE CONTINUOUS QUERY \"downsample\" ON \"$INFLUXDB_IML_STATS_DB\" BEGIN SELECT mean(*) INTO \"$INFLUXDB_IML_STATS_DB\".\"long_term\".:MEASUREMENT FROM /.*/ GROUP BY time(30m),* END"
influx -execute "ALTER RETENTION POLICY \"autogen\" ON \"$INFLUXDB_IML_STATS_DB\" DURATION 1d  REPLICATION 1 SHARD DURATION 2h DEFAULT" -database $INFLUXDB_IML_STATS_DB
