#!/bin/bash -ex

if $JENKINS && ! ${VAGRANT:-false}; then
    PROVISIONER=${PROVISIONER:?"Need to specify a PROVISIONER string"}
    BUILD_JOB_NAME=${BUILD_JOB_NAME:?"Need to set BUILD_JOB_NAME"}
    BUILD_JOB_BUILD_NUMBER=${BUILD_JOB_BUILD_NUMBER:?"Need to set BUILD_JOB_BUILD_NUMBER"}
    IEEL_VERSION=${IEEL_VERSION:?"Need to set IEEL_VERSION"}
    TEST_DISTRO_NAME=${TEST_DISTRO_NAME:?"Need to set TEST_DISTRO_NAME"}
fi
TEST_DISTRO_VERSION=${TEST_DISTRO_VERSION:?"Need to set TEST_DISTRO_VERSION"}
CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:?"Need to specify a CLUSTER_CONFIG_TEMPLATE path"}
CLUSTER_CONFIG=${CLUSTER_CONFIG:?"Need to specify a CLUSTER_CONFIG path to output the test json after provisioning"}

if ! $JENKINS || ${VAGRANT:-false}; then
    export BUILD_JOB_NAME="foo"
    export BUILD_JOB_BUILD_NUMBER=0
    cp $CLUSTER_CONFIG_TEMPLATE{,.tmp}
    CLUSTER_CONFIG_TEMPLATE="${CLUSTER_CONFIG_TEMPLATE}.tmp"
fi
# Fill in the Jenkins Build Job and Build Number, the IEEL version under test, and what OS to test it on.
sed -i -e "s/BUILD_JOB_NAME/${OVERRIDE_BUILD_JOB_NAME:-$BUILD_JOB_NAME}/g" \
       -e "s/BUILD_JOB_BUILD_NUMBER/${OVERRIDE_BUILD_JOB_BUILD_NUMBER:-$BUILD_JOB_BUILD_NUMBER}/g" \
       -e "s/IEEL_VERSION/${IEEL_VERSION}/g" \
       -e "s/TEST_DISTRO_NAME/${TEST_DISTRO_NAME}/g" \
       -e "s/TEST_DISTRO_VERSION/${TEST_DISTRO_VERSION}/g" \
       $CLUSTER_CONFIG_TEMPLATE

# Pass the template through the test json to provisioner json interpreter
python $CHROMA_DIR/tests/framework/utils/provisioner_interface/test_json2provisioner_json.py $CLUSTER_CONFIG_TEMPLATE provisioner_input.json || (echo "test_json2provisioner_json.py failed. Input: `cat $CLUSTER_CONFIG_TEMPLATE`" && exit 1)
cat provisioner_input.json

if ! $VAGRANT; then
    # Actually call the provisioner. Once the command returns, provisioning is complete.
    rc=0
    PROVISION_START_TIME=$(date '+%s')
    cat provisioner_input.json | $PROVISIONER > provisioner_output.json || rc=${PIPESTATUS[1]}
    echo "$PWD" >&2
    touch "$WORKSPACE"/cluster_provisioned
    PROVISION_END_TIME=$(date '+%s')
    PROVISION_DURATION=$(( PROVISION_END_TIME-PROVISION_START_TIME ))
    echo "$PROVISION_DURATION" > $WORKSPACE/provision_duration.txt
    echo "Provision took $(( PROVISION_DURATION/60 )) minutes."

    # Check that the provisioning didn't error
    if [ $rc != 0 ] || [ ! -s provisioner_output.json ] || grep '"success": false' provisioner_output.json; then
        echo "Cluster provisioner failed"
        rm -f cluster_provisioned
        exit 1
    fi
else
    # set the correct Vagrant box for the
    # TEST_DISTRO_VERSION
    declare -A vagrant_centos_boxes=( [7.2]=1511
                                      [7.3]=1611
                                      [7.4]=1708
                                      [7.5]=1804
                                      [7.6]=1810
                                      [7.7]=9999 )

    if $JENKINS; then
        pushd $CHROMA_DIR
    fi
    sed -i -e "/override\.vm\.box_version/s/> [0-9][0-9]*, *< *[0-9][0-9]*/> ${vagrant_centos_boxes[$TEST_DISTRO_VERSION]}, < ${vagrant_centos_boxes[$(echo "$TEST_DISTRO_VERSION+.1" | bc)]}/" Vagrantfile

    make reset_cluster
    if $JENKINS; then
        popd
        if [ "$EXECUTOR_NUMBER" = "0" ]; then
           cluster="" # or a number > 0
        else
           cluster="$EXECUTOR_NUMBER"
        fi
        sed -e "s/@HOSTNAME@/${HOSTNAME%%.*}/g"                              \
            -e "s/@VMHOST_ACCOUNT@/$USER/g"                                  \
            -e "s/@DOMAINNAME@/.$(domainname)/g"                             \
            -e "s/@VMHOST@/${HOSTNAME%%.*}/g"                                \
            -e "s/@CLUSTER@/$cluster/g"                                      \
            -e "s/@CLUSTER_NUM@/"$EXECUTOR_NUMBER"/g"                        \
            -e "s/@HOST_IP_ADDRESS@/$(host "$HOSTNAME" | sed 's/.* //')/g"   \
            -e "s/@VM2_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"2 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM3_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"3 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM4_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"4 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM5_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"5 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM6_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"6 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM7_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"7 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM8_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"8 |  \
                                    sed 's/.* //')/g"                        \
            -e "s/@VM9_IPADDRESS@/$(host "${HOSTNAME%%.*}"vm"${cluster}"9 |  \
                                    sed 's/.* //')/g"                        \
            < "$CHROMA_DIR"/provisioner_output-vagrant-"${MAKE_TARGET%_tests}".json.in \
            > provisioner_output.json
    else
        sed -e "s/@HOSTNAME@//g"                     \
            -e "s/@VMHOST_ACCOUNT@/$USER/g"          \
            -e "s/@DOMAINNAME@//g"                   \
            -e "s/@VMHOST@/host/g"                   \
            -e "s/@CLUSTER@//g"                      \
            -e "s/@CLUSTER_NUM@/0/g"                 \
            -e "s/@HOST_IP_ADDRESS@/192.168.121.1/g" \
            -e "s/@VM2_IPADDRESS@/10.73.10.32/g"     \
            -e "s/@VM3_IPADDRESS@/10.73.10.10/g"     \
            -e "s/@VM4_IPADDRESS@/10.73.10.8/g"      \
            -e "s/@VM5_IPADDRESS@/10.73.10.21/g"     \
            -e "s/@VM6_IPADDRESS@/10.73.10.22/g"     \
            -e "s/@VM7_IPADDRESS@/10.73.10.23/g"     \
            -e "s/@VM8_IPADDRESS@/10.73.10.24/g"     \
            -e "s/@VM9_IPADDRESS@/10.73.10.39/g"     \
            -e "s/@VM2_IPADDRESS@/10.73.20.32/g"     \
            -e "s/@VM5_LNETADDRESS@/10.73.20.21/g"   \
            -e "s/@VM6_LNETADDRESS@/10.73.20.22/g"   \
            -e "s/@VM7_LNETADDRESS@/10.73.20.23/g"   \
            -e "s/@VM8_LNETADDRESS@/10.73.20.24/g"   \
            < "$CHROMA_DIR"/provisioner_output-vagrant-"${MAKE_TARGET%_tests}".json.in \
            > provisioner_output.json
    fi
fi

# Pass the provisioner output back through an interpreter back to our test json format
if ! python $CHROMA_DIR/tests/framework/utils/provisioner_interface/provisioner_json2test_json.py provisioner_output.json $CLUSTER_CONFIG; then
    echo "provisioner_json2test_json.py failed. Input: $(cat provisioner_output.json)"
    exit 1
fi

cat provisioner_output.json