jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04

        ${{ if parameters.cross }}:
          MacOS:
            vmImage: macOS-10.13
          Windows:
            vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
      - template: azure-install-rust.yml
        parameters:
          rust_version: stable

      - task: Docker@1
        displayName: RabbitMQ
        inputs:
          command: run
          imageName: rabbitmq:3.6
          runInBackground: true
          ports: |
            5672:5672

      - script: |
          cargo test
        env:
          LOOM_MAX_DURATION: 10
          CI: "True"
        displayName: cargo test
