jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04

        ${{ if parameters.cross }}:
          MacOS:
            vmImage: macOS-10.13
          Windows:
            vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:

      - template: azure-install-rust.yml
        parameters:
          rust_version: nightly

      - template: azure-install-lustre.yml
        parameters:
          lustre_version: 2.10.7

      - template: azure-install-rabbit.yml

      - script: |
          set -e
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
          cargo test
          cargo tarpaulin
        env:
          LOOM_MAX_DURATION: 10
          CI: "True"
        displayName: cargo test
        ${{ if parameters.crate }}:
          workingDirectory: $(Build.SourcesDirectory)/${{ parameters.crate }}
