trigger:
  branches:
    include:
      - master
  tags:
    exclude:
      - v*

jobs:
  # Continuous Release to Devel Copr
  - template: template/azure-release.yml
    parameters:
      name: copr_devel_push
      displayName: Copr Devel Push
      project: manager-for-lustre-devel
      package: rust-iml
      spec: rust-iml.spec
      release: false

  # Wasm-Components Continuous Release to Devel Copr
  - template: template/azure-release.yml
    parameters:
      name: wasm_components_copr_devel_push
      displayName: Wasm Components Copr Devel Push
      project: manager-for-lustre-devel
      package: iml-wasm-components
      spec: iml-wasm-components.spec
      crate: iml-wasm-components
      release: false