#!/bin/bash -ex

. $CHROMA_DIR/tests/framework/utils/collect_reports.sh

spacelist_to_commalist() {
    echo $@ | tr ' ' ','
}

[ -r localenv ] && . localenv

TEST_SPECIFIC_CLUSTER_CONFIG=${TEST_SPECIFIC_CLUSTER_CONFIG:-"$(ls $PWD/existing_filesystem_configuration_cluster_cfg.json)"}
XML_RESULTS_FILE=${XML_RESULTS_FILE:-"~/test_report.xml"}
CHROMA_DIR=${CHROMA_DIR:-"$PWD/integrated-manager-for-lustre/"}

eval $(python $CHROMA_DIR/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

MEASURE_COVERAGE=${MEASURE_COVERAGE:-true}
TESTS=${TESTS:-"tests/integration/existing_filesystem_configuration/"}

trap "set +e; collect_reports" EXIT

echo "Begin running tests..."

scp $TEST_SPECIFIC_CLUSTER_CONFIG root@$TEST_RUNNER:/root/cluster_cfg.json

ssh root@$TEST_RUNNER "exec 2>&1; set -xe
cd /usr/share/chroma-manager/
unset http_proxy; unset https_proxy
./tests/integration/run_tests -f -c /root/cluster_cfg.json -x $XML_RESULTS_FILE $TESTS"

echo "End running tests."
