#!/bin/bash -ex

[ -r localenv ] && . localenv

ARCHIVE_NAME=ieel-$IEEL_VERSION.tar.gz
CHROMA_DIR=${CHROMA_DIR:-"$PWD/chroma/"}
CLUSTER_CONFIG=${CLUSTER_CONFIG:-"$CHROMA_DIR/chroma-manager/tests/framework/gui/selenium_cluster_config.json"}

eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

MEASURE_COVERAGE=${MEASURE_COVERAGE:-false}

echo "Beginning installation and setup..."

ssh root@$TEST_RUNNER <<EOF
set -ex
yum install --setopt=retries=50 --setopt=timeout=180 -y unzip tar bzip2 gcc make tigervnc-server git firefox
yum update --setopt=retries=50 --setopt=timeout=180 -y nss

yum install -y google-chrome-stable

# Create a user so we can run the tests as non-root
useradd chromatest
su chromatest <<EOC
mkdir -p ~/.ssh
touch ~/.ssh/authorized_keys
EOC
cat .ssh/id_rsa.pub >> /home/chromatest/.ssh/authorized_keys
cp .ssh/* ~chromatest/.ssh/
chown chromatest.chromatest ~chromatest/.ssh/*
chmod 600 ~chromatest/.ssh/*
EOF

# Copy the repo to the test node (don't want to have to clone every test run - impacts Gerrit)
# We exclude chroma-externals and copy just what we need to reduce the io load on our builders.
(tar -czf - --exclude='chroma/chroma-externals*' .; tar -czf - $(sed -e 's|^|chroma/chroma-externals/|' < chroma/chroma-manager/tests/framework/gui/test_dependencies)) | ssh chromatest@$TEST_RUNNER "mkdir -p chroma_test_env; cd chroma_test_env; tar -xizf -"

ssh chromatest@$TEST_RUNNER <<"EOF"
set -ex

mkdir $HOME/bin

MANAGER_DIR=${MANAGER_DIR:-"$HOME/chroma_test_env/chroma/chroma-manager"}
ZIPLOCK_DIR=${ZIPLOCK_DIR:-"$MANAGER_DIR/ui-modules/node_modules/intel-ziplocker"}
CHROMA_EXTERNALS=${CHROMA_EXTERNALS:-"$HOME/chroma_test_env/chroma/chroma-externals"}

cd chroma_test_env/chroma/chroma-manager

# Install npm-based requirements
export ZIP_DEV=true
make ui-modules

# Configure VNC server
cd ~
vncpasswd <<EOC
somepassword
somepassword
EOC
EOF

echo "End installation and setup."
