#!/bin/bash -ex

[ -r localenv ] && . localenv

ARCHIVE_NAME=ieel-$IEEL_VERSION.tar.gz
CHROMA_DIR=${CHROMA_DIR:-"$PWD/chroma/"}
CLUSTER_CONFIG=${CLUSTER_CONFIG:-"$CHROMA_DIR/chroma-manager/tests/framework/gui/selenium_cluster_config.json"}

eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

MEASURE_COVERAGE=${MEASURE_COVERAGE:-false}
GOOGLE_REPO=${GOOGLE_REPO:-"http://cobbler/cobbler/repo_mirror/google_chrome-stable-x86_64"}  # If not on Toro, can pass in http://dl.google.com/linux/chrome/rpm/stable/x86_64

echo "Beginning installation and setup on $CHROMA_MANAGER..."

ssh root@$TEST_RUNNER <<EOF
set -ex
yum install --setopt=retries=50 --setopt=timeout=180 -y unzip tar bzip2 python-virtualenv python-devel gcc make tigervnc-server npm git firefox java-1.7.0-openjdk haveged
yum update --setopt=retries=50 --setopt=timeout=180 -y nss

# Selenium server needs entropy
service haveged start

if [ ! -z "$GOOGLE_REPO" ]; then
  # Install Google Chrome
  cat << EOC >> /etc/yum.repos.d/google.repo
[google]
name=Google
baseurl=$GOOGLE_REPO
enabled=0
gpgcheck=0
retries=50
timeout=180
EOC
  yum --enablerepo=google install -y google-chrome-stable
fi

# Create a user so we can run the tests as non-root
useradd chromatest
su chromatest <<EOC
mkdir -p ~/.ssh
touch ~/.ssh/authorized_keys
EOC
cat .ssh/id_rsa.pub >> /home/chromatest/.ssh/authorized_keys
cp .ssh/* ~chromatest/.ssh/
chown chromatest.chromatest ~chromatest/.ssh/*
chmod 600 ~chromatest/.ssh/*
EOF

# Copy the repo to the test node (don't want to have to clone every test run - impacts Gerrit)
# We exclude chroma-externals and copy just what we need to reduce the io load on our builders.
(tar -czf - --exclude='chroma/chroma-externals*' .; tar -czf - $(sed -e 's|^|chroma/chroma-externals/|' < chroma/chroma-manager/tests/framework/gui/test_dependencies)) | ssh chromatest@$TEST_RUNNER "mkdir -p chroma_test_env; cd chroma_test_env; tar -xizf -"

ssh chromatest@$TEST_RUNNER <<"EOF"
set -ex

mkdir $HOME/bin

MANAGER_DIR=${MANAGER_DIR:-"$HOME/chroma_test_env/chroma/chroma-manager"}
ZIPLOCK_DIR=${ZIPLOCK_DIR:-"$MANAGER_DIR/ui-modules/node/ziplocker"}
CHROMA_EXTERNALS=${CHROMA_EXTERNALS:-"$HOME/chroma_test_env/chroma/chroma-externals"}
ZIP_INSTALL_DEV=${ZIP_INSTALL_DEV:-"$ZIPLOCK_DIR/bin/zip-install-dev --overrides.ziplockDir=$CHROMA_EXTERNALS"}

# Install Chromedriver
LATEST_CHROMEDRIVER_RELEASE=$(curl -f http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
wget http://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_RELEASE/chromedriver_linux64.zip
unzip chromedriver_linux64.zip -d $HOME/bin/

# Install Selenium
selenium_filename="selenium-server-standalone-*.jar"
num_matching_files=$(find chroma_test_env/chroma/chroma-externals/ -maxdepth 1 -name "$selenium_filename" | wc -l)
if [ $num_matching_files != 1 ]; then
    echo "Expected to find exactly 1 match for $selenium_filename in chroma-externals, but found $num_matching_files"
    ls chroma_test_env/chroma/chroma-externals/$selenium_filename
fi
cp chroma_test_env/chroma/chroma-externals/$selenium_filename $HOME/bin/selenium-server-standalone.jar

# Set up the virtualenv to run the tests in
cd chroma_test_env
virtualenv --no-site-packages .
source bin/activate
cd chroma/chroma-manager

python tests/utils/pip_install_requirements.py ../chroma-externals/ ../chroma-externals/*.tar.gz

# Install npm-based requirements
cd $ZIPLOCK_DIR
cp -r $CHROMA_EXTERNALS/ziplocker/node_modules/ ./node_modules/
$ZIP_INSTALL_DEV

PATHS_TO_INSTALL="ui-modules/node/router/
ui-modules/node/srcmap-reverse
ui-modules/node/stub-daddy/
ui-modules/node/stub-daddy-client/
ui-modules/node/dirp/
ui-modules/node/req/
ui-modules/isomorphic/fp/
ui-modules/isomorphic/obj/
realtime/
ui-modules/node/view-server/
chroma_ui/
chroma_ui_new
chroma_ui_new/gulp
ui-modules/browser/socket-worker"

for install_path in $PATHS_TO_INSTALL
do
    cd $MANAGER_DIR/$install_path
    $ZIP_INSTALL_DEV
done

# Configure VNC server
cd ~
vncpasswd <<EOC
somepassword
somepassword
EOC
EOF

# Install and setup chroma manager
scp ../$ARCHIVE_NAME $CHROMA_DIR/chroma-manager/tests/utils/install.exp root@$CHROMA_MANAGER:/tmp
ssh root@$CHROMA_MANAGER "#don't do this, it hangs the ssh up, when used with expect, for some reason: exec 2>&1
set -ex
cat << \"EOF\" >> /etc/yum.repos.d/autotest.repo
retries=50
timeout=180
EOF
yum install -y python-mock expect
if $MEASURE_COVERAGE; then
    yum install -y python-coverage
fi
rm -f /etc/yum.repos.d/autotest.repo
yum clean metadata
# Install from the installation package
cd /tmp
tar xzvf $ARCHIVE_NAME
cd $(basename $ARCHIVE_NAME .tar.gz)
if ! expect ../install.exp $CHROMA_USER $CHROMA_EMAIL $CHROMA_PASS ${CHROMA_NTP_SERVER:-localhost}; then
    rc=${PIPESTATUS[0]}
    cat /var/log/chroma/install.log
    exit $rc
fi

cat <<\"EOF1\" > /usr/share/chroma-manager/local_settings.py
import logging
import sys
import settings
from scripts.nginx_settings import get_production_nginx_settings
LOG_LEVEL = logging.DEBUG
MIDDLEWARE_CLASSES = settings.MIDDLEWARE_CLASSES + ('tests.request_logging_middleware.RequestLoggingMiddleware',)
DEBUG = True
TEMPLATE_DEBUG = False
LOG_PATH = \"/var/log/chroma\"
CRYPTO_FOLDER = \"/var/lib/chroma\"
STORAGE_PLUGIN_DEBUG = False
for key, value in get_production_nginx_settings().items():
    setattr(sys.modules[__name__], key, value)
EOF1

mkdir -p /usr/share/chroma-manager/tests/framework/gui/"

scp -r chroma/chroma-manager/tests/request_logging_middleware.py root@$CHROMA_MANAGER:/usr/share/chroma-manager/tests/request_logging_middleware.py
scp -r chroma/chroma-manager/tests/framework/gui/mock_agent root@$CHROMA_MANAGER:/usr/share/chroma-manager/tests/framework/gui/mock_agent
scp -r chroma/chroma-manager/tests/unit/ root@$CHROMA_MANAGER:/usr/share/chroma-manager/tests/unit
scp chroma/chroma-manager/tests/__init__.py root@$CHROMA_MANAGER:/usr/share/chroma-manager/tests/__init__.py

# copy the .py's that where stripped (HYD-1849)
scp chroma/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py root@$CHROMA_MANAGER:/usr/share/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py
scp chroma/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py root@$CHROMA_MANAGER:/usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py

ssh root@$CHROMA_MANAGER "exec 2>&1; set -ex
# patch the agent
cat /usr/share/chroma-manager/tests/framework/gui/mock_agent/agent_rpc_addon.py >> /usr/share/chroma-manager/chroma_core/services/job_scheduler/agent_rpc.py

# patch the plugin manager
cat /usr/share/chroma-manager/tests/framework/gui/mock_agent/agent_daemon_addon.py >> /usr/share/chroma-manager/chroma_core/services/plugin_runner/agent_daemon.py

if $MEASURE_COVERAGE; then
  cat <<\"EOF1\" > /usr/share/chroma-manager/.coveragerc
[run]
data_file = /var/tmp/.coverage
parallel = True
source = /usr/share/chroma-manager/
EOF1
  cat <<\"EOF1\" > /usr/lib/python2.6/site-packages/sitecustomize.py
import coverage
cov = coverage.coverage(config_file='/usr/share/chroma-manager/.coveragerc', auto_data=True)
cov.start()
cov._warn_no_data = False
cov._warn_unimported_source = False
EOF1
fi

chroma-config restart
"

echo "End installation and setup."
