#!/bin/bash
set -x

[ -r localenv ] && . localenv

CHROMA_DIR=${CHROMA_DIR:-"$PWD/chroma/"}
CLUSTER_CONFIG=${CLUSTER_CONFIG:-"$CHROMA_DIR/chroma-manager/tests/framework/gui/selenium_cluster_config.json"}

eval $(python $CHROMA_DIR/chroma-manager/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

trap "set +e; scp -r chromatest@$TEST_RUNNER:test_reports $WORKSPACE" EXIT

scp $CLUSTER_CONFIG chromatest@$TEST_RUNNER:cluster_config.json
ssh chromatest@$TEST_RUNNER <<EOC
set -ex
mkdir test_reports
vncserver :1 -geometry 1024x768
export DISPLAY=\$(hostname):1

#######################################
# New UI Tests
#######################################

# Run Karma GUI unit tests (new ui)
cd \$HOME/chroma_test_env/chroma/chroma-manager/chroma_ui_new
./node_modules/karma/bin/karma start --browsers Chrome,Firefox --singleRun true --reporters dots,junit
mv test-results.xml \$HOME/test_reports/karma-test-results-new-ui.xml

# Run Sourcemap Generation Integration Test(s)
cd \$HOME/chroma_test_env/chroma/chroma-manager/chroma_ui_new
./node_modules/.bin/mjnw --reportType=junit --JUnitReportSavePath=\$HOME/test_reports/ --JUnitReportFilePrefix=srcmap-generation-results

# Run ziplocker tests
cd \$HOME/chroma_test_env/chroma/chroma-manager/ui-modules/node/ziplocker
./node_modules/.bin/mjnw --reportType=junit --JUnitReportSavePath=\$HOME/test_reports/ --JUnitReportFilePrefix=ziplocker-results

# Run Stub Daddy Mock API Service unit tests
cd \$HOME/chroma_test_env/chroma/chroma-manager/ui-modules/node/stub-daddy
./node_modules/.bin/mjnw --reportType=junit --JUnitReportSavePath=\$HOME/test_reports/ --JUnitReportFilePrefix=stub-daddy-results

# Run socket-router tests
cd \$HOME/chroma_test_env/chroma/chroma-manager/ui-modules/node/socket-router
./node_modules/.bin/mjnw --reportType=junit --JUnitReportSavePath=\$HOME/test_reports/ --JUnitReportFilePrefix=socket-router-results

# Run realtime module tests (new ui)
cd \$HOME/chroma_test_env/chroma/chroma-manager
cat << EOF > ./realtime/conf.json
{
  "SERVER_HTTP_URL": "https://localhost:8000/",
  "PRIMUS_PORT": 8888
}
EOF
cd \$HOME/chroma_test_env/chroma/chroma-manager/ui-modules/node/stub-daddy
node ./ --overrides.port=8000 > /dev/null &
STUB_DADDY_ID=\$!
cd \$HOME/chroma_test_env/chroma/chroma-manager/realtime
node ./ > /dev/null &
REALTIME_ID=\$!
./node_modules/.bin/jasmine-node --verbose --captureExceptions --junitreport --output \$HOME/test_reports/ ./test/ || true
kill -9 \$REALTIME_ID
kill -9 \$STUB_DADDY_ID

# Run srcmap-reverse tests
cd \$HOME/chroma_test_env/chroma/chroma-manager/ui-modules/node/srcmap-reverse
./node_modules/.bin/mjnw --reportType=junit --JUnitReportSavePath=\$HOME/test_reports/ --JUnitReportFilePrefix=srcmap-reverse-results


#######################################
# Old UI Tests
#######################################

# Run Karma GUI unit tests (old ui)
cd \$HOME/chroma_test_env/chroma/chroma-manager/chroma_ui
./node_modules/karma/bin/karma start --browsers Chrome,Firefox --singleRun true --reporters dots,junit
mv test-results.xml \$HOME/test_reports/karma-test-results-old-ui.xml
EOC

NUM_EXPECTED_TEST_REPORTS=32
NUM_TEST_REPORTS=$(ssh chromatest@$TEST_RUNNER 'ls -l test_reports' | grep -v "^total " | wc -l)
if [ $NUM_TEST_REPORTS -ne $NUM_EXPECTED_TEST_REPORTS ]; then
    echo "Incorrect number of test reports. Possible sources include a catastrophic error running one of the test suites, or adding a new test set that causes there to be an new xml file. Expected $NUM_EXPECTED_TEST_REPORTS, but found $NUM_TEST_REPORTS."
    exit 1
else
    exit 0
fi
