#!/bin/bash -ex

make substs
. tests/framework/utils/defaults.sh
. tests/framework/utils/selective_auto_pass.sh
. tests/framework/utils/cleanup.sh

set_defaults false
check_for_autopass

CHROMA_DIR="$PWD"

export CLUSTER_CONFIG_TEMPLATE=${CLUSTER_CONFIG_TEMPLATE:-"$CHROMA_DIR/tests/framework/integration/existing_filesystem_configuration/existing_filesystem_configuration_cluster_cfg.json"}

cd $WORKSPACE

got_aborted=false
# Gather logs from nodes and release the cluster at exit
trap "set +e; cleanup" EXIT

trap "set -x
got_aborted=true
echo \"Got SIGTERM\"
ps axf
exit 1" TERM

$CHROMA_DIR/tests/framework/utils/provisioner_interface/provision_cluster

# see if this cures the 401 errors from jenkins
eval $(python $CHROMA_DIR/tests/utils/json_cfg2sh.py "$CLUSTER_CONFIG")

$CHROMA_DIR/tests/framework/integration/existing_filesystem_configuration/cluster_setup

setup_rc=0
test_run_rc=0
for dne in false true; do
    for test_ha in false true; do
        if $test_ha; then
            device_types_to_test=(linux)
        else
            #devices_to_test=(zfs lvm mdraid linux); do  <--- mdraid Coming soon.
            device_types_to_test=(zfs lvm linux)
        fi

        for device_type in ${device_types_to_test[@]}; do
            echo "Beginning automated ${device_type} run..."

            export TEST_SPECIFIC_CLUSTER_CONFIG=$PWD/existing_filesystem_configuration_cluster_cfg_${device_type}_HA_is_${test_ha}_dne_is_${dne}.json

            sed -e "s/\(\"device_type\": *\)\"linux\"/\1\"${device_type}\"/g" $CLUSTER_CONFIG > $TEST_SPECIFIC_CLUSTER_CONFIG
            sed -i -e "s/\(\"backend_filesystem\": *\)\"ldiskfs\"/\1\"${device_type}\"/g" $TEST_SPECIFIC_CLUSTER_CONFIG
            sed -i -e "s/\(\"test_ha\"\: *\)true/\1${test_ha}/g" $TEST_SPECIFIC_CLUSTER_CONFIG

            # One Kind entry is defined as "kind": "OSTorMDT" set it to be an OST for !dne or an MDT for dne
            # The replace actually does a number of things such as the mount point etc.
            if $dne; then
                sed -i -e s/OSTorMDT/MDT/g $TEST_SPECIFIC_CLUSTER_CONFIG
                sed -i -e s/ostORmdt/mdt/g $TEST_SPECIFIC_CLUSTER_CONFIG
            else
                sed -i -e s/OSTorMDT/OST/g $TEST_SPECIFIC_CLUSTER_CONFIG
                sed -i -e s/ostORmdt/ost/g $TEST_SPECIFIC_CLUSTER_CONFIG
            fi

            export XML_RESULTS_FILE="~/test_report_${device_type}_HA_is_${test_ha}.xml"

            # Don't stop on error for this case because if one iteration of this loop fails we still want to perform the other iterations
            cat $TEST_SPECIFIC_CLUSTER_CONFIG
            if ! $CHROMA_DIR/tests/framework/integration/existing_filesystem_configuration/filesystem_setup; then
                let setup_rc+=${PIPESTATUS[0]}
                echo "Automated ${device_type} setup failed"
                exit 1
            fi
            if ! $CHROMA_DIR/tests/framework/integration/existing_filesystem_configuration/run_tests; then
                let test_run_rc+=${PIPESTATUS[0]}
                echo "Automated ${device_type} run failed"
                exit 1
            fi
            echo "Automated ${device_type} run complete."
        done
    done
done

if [ $setup_rc -gt 0 -o $test_run_rc -gt 0 ]; then
    echo "One or more iterations failed"
    exit 1
fi

echo "Automated efs run complete."

# Combine coverage reports from the different nodes.
if $MEASURE_COVERAGE; then
  ls .coverage*
  # https://github.com/pypa/virtualenv/issues/355
  python_version=$(python -c 'import platform; print ".".join(platform.python_version_tuple()[0:2])')
  echo "
[paths]
source1 =
    $WORKSPACE/$CHROMA_DIR/chroma-manager/
    /usr/share/chroma-manager/
source2 =
    $WORKSPACE/$CHROMA_DIR/chroma-agent/chroma_agent/
    /usr/lib/python$python_version/site-packages/chroma_agent/

[report]
include =
    $WORKSPACE/$CHROMA_DIR/*
omit =
    *junk.py
    */tests/*
" > .coveragerc

  coverage combine
  coverage report -m
  coverage xml --ignore-errors
fi
