LOCATION := http://fedora.osuosl.org/linux/updates/testing/18/SRPMS/python-coverage-3.5.3-2.fc18.src.rpm
REQUIREMENT := http://github.com/kprantis/coverage/tarball/master\#egg=coverage

include ../include/Makefile.rpm
