LOCATION := http://fedora.osuosl.org/linux/updates/testing/18/SRPMS/python-coverage-3.5.3-2.fc18.src.rpm
REQUIREMENT := https://github.com/kprantis/coverage/archive/coverage-3.5.2pl2.tar.gz

include ../include/Makefile.rpm
