LOCATION := http://dl.fedoraproject.org/pub/fedora/linux/releases/18/Everything/source/SRPMS/p/python-coverage-3.5.3-2.fc18.src.rpm
REQUIREMENT := https://dl.dropboxusercontent.com/s/qqjud11bvh8vo68/coverage-coverage-3.5.2pl2.tar.gz

include ../include/Makefile.rpm
