# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 02:19
from __future__ import unicode_literals
from django.db import migrations

# Current stats implementations was reliant on there not being a primary key set in the db.
# Even though one was set in the model.
#
# This bug is now fixed, so we need to remove the pk constraint to keep inserts functional.

stat_tables = map(
    lambda x: "ALTER TABLE {0} DROP CONSTRAINT {0}_pkey;".format(x),
    [
        "chroma_core_sample_10",
        "chroma_core_sample_60",
        "chroma_core_sample_300",
        "chroma_core_sample_3600",
        "chroma_core_sample_86400",
    ],
)


class Migration(migrations.Migration):

    dependencies = [("chroma_core", "0001_initial")]

    operations = [migrations.RunSQL("\n".join(stat_tables))]
