# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("chroma_core", "0005_add_table_json_notify")]

    operations = [
        migrations.CreateModel(
            name="UpdateYumFileJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.Job",
                    ),
                ),
                ("host", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chroma_core.ManagedHost")),
            ],
            bases=("chroma_core.job",),
        )
    ]
