# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("chroma_core", "0006_device_devicehost")]

    operations = [
        migrations.CreateModel(
            name="NtpOutOfSyncAlert",
            fields=[
                (
                    "alertstatebase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.AlertStateBase",
                    ),
                )
            ],
            options={},
            bases=("chroma_core.alertstatebase",),
        )
    ]
