# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 12:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0010_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text=b"Unique identifer per-device", max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("size", models.CharField(help_text=b"The size of the device in bytes", max_length=64)),
                ("usable_for_lustre", models.BooleanField(help_text=b"Is this storage device usable for Lustre")),
                ("device_type", models.CharField(help_text=b"The type of block or virtual device", max_length=64)),
                (
                    "parents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), help_text=b"A list of parent devices", size=None
                    ),
                ),
                (
                    "children",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), help_text=b"A list of child devices", size=None
                    ),
                ),
                ("max_depth", models.SmallIntegerField(help_text=b"Maximum depth where the device is nested")),
                ("record_id", models.IntegerField(help_text=b"A simple ID for warpdrive cache to use")),
            ],
        ),
        migrations.CreateModel(
            name="DeviceHost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(help_text=b"Unique identifer per-device", max_length=255)),
                ("fqdn", models.CharField(help_text=b"The fqdn this device may reside on", max_length=255)),
                ("local", models.BooleanField(help_text=b"Is the device local to this node")),
                (
                    "paths",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        help_text=b"A list of paths to access a device",
                        size=None,
                    ),
                ),
                (
                    "mount_path",
                    models.CharField(help_text=b"The mounted path of the device", max_length=255, null=True),
                ),
                ("fs_type", models.CharField(help_text=b"The fs type of the device", max_length=255, null=True)),
                ("fs_label", models.CharField(help_text=b"The fs label on the device", max_length=255, null=True)),
                ("fs_uuid", models.CharField(help_text=b"The fs uuid on the device", max_length=255, null=True)),
            ],
        ),
    ]
