# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0011_device_devicehost'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='record_id',
            field=models.IntegerField(help_text=b'Integer id for cache in warp-drive to use', null=True),
        ),
    ]
