# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0013_device_devicehost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagealertpropagated',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storagealertpropagated',
            name='alert_state',
        ),
        migrations.RemoveField(
            model_name='storagealertpropagated',
            name='storage_resource',
        ),
        migrations.DeleteModel(
            name='StorageAlertPropagated',
        ),
    ]
