# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-10 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0013_auto_20200317_1809"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleTimeSyncAlert",
            fields=[],
            options={"proxy": True, "indexes": [],},
            bases=("chroma_core.alertstatebase",),
        ),
        migrations.CreateModel(
            name="NoTimeSyncAlert",
            fields=[],
            options={"proxy": True, "indexes": [],},
            bases=("chroma_core.alertstatebase",),
        ),
        migrations.CreateModel(
            name="TimeOutOfSyncAlert",
            fields=[],
            options={"proxy": True, "indexes": [],},
            bases=("chroma_core.alertstatebase",),
        ),
        migrations.CreateModel(
            name="UnknownTimeSyncAlert",
            fields=[],
            options={"proxy": True, "indexes": [],},
            bases=("chroma_core.alertstatebase",),
        ),
    ]
