# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-21 15:42
from __future__ import unicode_literals

import chroma_core.models.action_queue
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from chroma_core.migrations import forward_lustre_fid, backward_lustre_fid


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0015_device"),
    ]

    operations = [
        migrations.RunSQL(sql=forward_lustre_fid, reverse_sql=backward_lustre_fid),
        migrations.CreateModel(
            name="ActionType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="FidActionQueue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fid", chroma_core.models.action_queue.LustreFidField()),
                ("entries", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ("failed", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mailboxes",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("start", models.DateTimeField()),
                ("finish", models.DateTimeField()),
                ("state", models.CharField(max_length=16)),
                ("fids_total", models.BigIntegerField(default=0)),
                ("fids_completed", models.BigIntegerField(default=0)),
                ("fids_failed", models.BigIntegerField(default=0)),
                ("data_transfered", models.BigIntegerField(default=0)),
                ("keep_failed", models.BooleanField(default=True)),
                (
                    "actions",
                    django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None),
                ),
                ("args", django.contrib.postgres.fields.jsonb.JSONField(default={})),
                (
                    "filesystem",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chroma_core.ManagedFilesystem"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fidactionqueue",
            name="mailbox",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chroma_core.Mailboxes"),
        ),
        migrations.AlterUniqueTogether(name="actiontype", unique_together=set([("name",)]),),
    ]
