# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0016_device_devicehost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageresourceclassstatistic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storageresourceclassstatistic',
            name='resource_class',
        ),
        migrations.DeleteModel(
            name='StorageResourceClassStatistic',
        ),
    ]
