# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0016_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="SfaDiskDrive",
            fields=[
                ("index", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ("child_health_state", models.PositiveSmallIntegerField()),
                ("failed", models.BooleanField()),
                ("slot_number", models.PositiveIntegerField()),
                ("health_state", models.PositiveSmallIntegerField()),
                ("health_state_reason", models.TextField()),
                ("member_index", models.PositiveSmallIntegerField(null=True)),
                ("member_state", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SFADiskSlot",
            fields=[
                ("index", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                (
                    "disk_drive_index",
                    models.ForeignKey(
                        db_column=b"disk_drive_index",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chroma_core.SfaDiskDrive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SfaEnclosure",
            fields=[
                ("index", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ("element_name", models.TextField()),
                ("health_state", models.PositiveSmallIntegerField()),
                ("health_state_reason", models.TextField()),
                ("position", models.PositiveSmallIntegerField()),
                ("enclosure_type", models.PositiveSmallIntegerField()),
                ("canister_location", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SfaJob",
            fields=[
                ("index", models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ("sub_target_index", models.PositiveIntegerField(null=True)),
                ("sub_target_type", models.PositiveSmallIntegerField(null=True)),
                ("job_type", models.PositiveSmallIntegerField()),
                ("state", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SfaPowerSupply",
            fields=[
                ("index", models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ("health_state", models.PositiveSmallIntegerField()),
                ("health_state_reason", models.TextField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "enclosure_index",
                    models.ForeignKey(
                        db_column=b"enclosure_index",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chroma_core.SfaEnclosure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SfaStorageSystem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.TextField(unique=True)),
                ("health_state_reason", models.TextField()),
                ("health_state", models.PositiveSmallIntegerField()),
                ("child_health_state", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="sfapowersupply",
            name="storage_system",
            field=models.ForeignKey(
                db_column=b"storage_system",
                on_delete=django.db.models.deletion.CASCADE,
                to="chroma_core.SfaStorageSystem",
                to_field=b"uuid",
            ),
        ),
        migrations.AddField(
            model_name="sfajob",
            name="storage_system",
            field=models.ForeignKey(
                db_column=b"storage_system",
                on_delete=django.db.models.deletion.CASCADE,
                to="chroma_core.SfaStorageSystem",
                to_field=b"uuid",
            ),
        ),
        migrations.AddField(
            model_name="sfaenclosure",
            name="storage_system",
            field=models.ForeignKey(
                db_column=b"storage_system",
                on_delete=django.db.models.deletion.CASCADE,
                to="chroma_core.SfaStorageSystem",
                to_field=b"uuid",
            ),
        ),
        migrations.AddField(
            model_name="sfadiskslot",
            name="enclosure_index",
            field=models.ForeignKey(
                db_column=b"enclosure_index", on_delete=django.db.models.deletion.CASCADE, to="chroma_core.SfaEnclosure"
            ),
        ),
        migrations.AddField(
            model_name="sfadiskslot",
            name="storage_system",
            field=models.ForeignKey(
                db_column=b"storage_system",
                on_delete=django.db.models.deletion.CASCADE,
                to="chroma_core.SfaStorageSystem",
                to_field=b"uuid",
            ),
        ),
        migrations.AddField(
            model_name="sfadiskdrive",
            name="enclosure_index",
            field=models.ForeignKey(
                db_column=b"enclosure_index", on_delete=django.db.models.deletion.CASCADE, to="chroma_core.SfaEnclosure"
            ),
        ),
        migrations.AddField(
            model_name="sfadiskdrive",
            name="storage_system",
            field=models.ForeignKey(
                db_column=b"storage_system",
                on_delete=django.db.models.deletion.CASCADE,
                to="chroma_core.SfaStorageSystem",
                to_field=b"uuid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sfadiskslot", unique_together=set([("enclosure_index", "disk_drive_index")]),
        ),
    ]
