# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0017_device_devicehost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageresourceattributereference',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='storageresourceattributereference',
            name='value',
        ),
        migrations.DeleteModel(
            name='StorageResourceAttributeReference',
        ),
    ]
