# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 02:19
from __future__ import unicode_literals
from django.db import migrations
from chroma_core.migrations import (
    build_tables,
    forward_trigger_template,
    backward_trigger_template,
    join,
)


tables = map(
    build_tables,
    ["sfadiskdrive", "sfadiskslot", "sfaenclosure", "sfajob", "sfapowersupply", "sfastoragesystem", "sfacontroller"],
)

forward_trigger_list = map(forward_trigger_template, tables)
forward_trigger_str = join(forward_trigger_list)

backward_trigger_list = map(backward_trigger_template, tables)
backward_trigger_str = join(backward_trigger_list)


class Migration(migrations.Migration):

    dependencies = [("chroma_core", "0017_sfaenclosure_sfastoragesystem")]

    operations = [migrations.RunSQL(sql=forward_trigger_str, reverse_sql=backward_trigger_str)]
