# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-29 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0018_sfa_json_notify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sethostprofilejob",
            name="host",
        ),
        migrations.RemoveField(
            model_name="sethostprofilejob",
            name="server_profile",
        ),
        migrations.RemoveField(
            model_name="managedhost",
            name="properties",
        ),
        migrations.DeleteModel(
            name="SetHostProfileJob",
        ),
    ]
