# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0019_device_devicehost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplehistostorebin',
            name='histo_store_time',
        ),
        migrations.DeleteModel(
            name='SimpleHistoStoreBin',
        ),
    ]
