# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0021_device_devicehost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageresourcestatistic',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storageresourcestatistic',
            name='storage_resource',
        ),
        migrations.DeleteModel(
            name='StorageResourceStatistic',
        ),
    ]
