# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-11 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0022_fs_name_uniqueness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendstratagemresultstoclientjob',
            name='filesystem',
        ),
        migrations.RemoveField(
            model_name='sendstratagemresultstoclientjob',
            name='job_ptr',
        ),
        migrations.DeleteModel(
            name='SendStratagemResultsToClientJob',
        ),
    ]
