# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0022_device_devicehost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageresourcerecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storageresourcerecord',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='storageresourcerecord',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='storageresourcerecord',
            name='resource_class',
        ),
        migrations.RemoveField(
            model_name='storageresourcerecord',
            name='storage_id_scope',
        ),
        migrations.RemoveField(
            model_name='volumenode',
            name='storage_resource',
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='storage_resource',
        ),
        migrations.DeleteModel(
            name='StorageResourceRecord',
        ),
    ]
