# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-10 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0023_device_devicehost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageresourceclass',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storageresourceclass',
            name='storage_plugin',
        ),
        migrations.DeleteModel(
            name='StorageResourceClass',
        ),
    ]
