# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-31 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0025_createsnapshotjob_destroysnapshotjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="runstratagemjob",
            name="search_expression",
            field=models.TextField(null=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="runstratagemjob",
            name="action",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
