# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-13 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0011_auth_json_notify'),
        ('chroma_core', '0025_device_devicehost'),
    ]

    operations = [
    ]
