# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-15 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0026_runstratagemjob_search_expression"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastFileScanMdtJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.Job",
                    ),
                ),
                ("fqdn", models.CharField(help_text=b"MDT host to perform scan on", max_length=256)),
                ("uuid", models.CharField(max_length=64)),
                ("fsname", models.CharField(max_length=8)),
                ("config", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=("chroma_core.job",),
        ),
        migrations.CreateModel(
            name="ScanMdtJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.Job",
                    ),
                ),
                ("fqdn", models.CharField(help_text=b"MDT host to perform scan on", max_length=256)),
                ("uuid", models.CharField(max_length=64)),
                ("fsname", models.CharField(max_length=8)),
                ("config", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=("chroma_core.job",),
        ),
    ]
