# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-01 17:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0027_add_scan_mdt_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigureLDevJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.Job",
                    ),
                ),
                ("ldev_entries", django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("chroma_core.job",),
        ),
    ]
