# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0027_add_scan_mdt_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcertificate",
            name="serial",
            field=models.CharField(max_length=40),
        ),
    ]
