# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0028_device_devicehost_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='size',
            field=models.BigIntegerField(help_text=b'The size of the device in bytes'),
        ),
    ]
