# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0028_expand_client_serial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="managedtarget",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="managedtarget",
            name="active_mount",
        ),
        migrations.RemoveField(
            model_name="managedtargetmount",
            name="host",
        ),
        migrations.RemoveField(
            model_name="managedtargetmount",
            name="target",
        ),
        migrations.RemoveField(
            model_name="managedtargetmount",
            name="volume_node",
        ),
        migrations.DeleteModel(
            name="ManagedTargetMount",
        ),
    ]
