# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-20 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0013_auto_20200317_1809'),
        ('chroma_core', '0029_device_size'),
    ]

    operations = [
    ]
