# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-26 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0030_merge_20200320_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedtarget',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chroma_core.Device'),
        ),
    ]
