# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0031_device_managedtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedtargetmount',
            name='volume_node',
        ),
        migrations.AddField(
            model_name='managedtargetmount',
            name='device_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chroma_core.DeviceHost'),
        ),
    ]
