# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0031_add_ticket_cluster_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForgetLustreClientJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chroma_core.Job",
                    ),
                ),
                ("old_state", models.CharField(max_length=32)),
                (
                    "lustre_client_mount",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chroma_core.LustreClientMount"),
                ),
            ],
            options={
                "ordering": ["id"],
            },
            bases=("chroma_core.job",),
        ),
    ]
