# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-11-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models

forward = """
UPDATE chroma_core_task SET fs_name = fs.name
        FROM chroma_core_managedfilesystem AS fs WHERE filesystem_id = fs.id;
UPDATE chroma_core_task SET running_on_fqdn = h.fqdn
        FROM chroma_core_managedhost AS h WHERE running_on_id = h.id;
"""
backward = """
UPDATE chroma_core_task SET filesystem_id = fs.id
        FROM chroma_core_managedfilesystem AS fs WHERE fs_name = fs.name AND fs.not_deleted = 't';
UPDATE chroma_core_task SET running_on_id = h.id
        FROM chroma_core_managedhost AS h WHERE running_on_fqdn = h.fqdn AND h.not_deleted = 't';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0032_forgetlustreclientjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="fs_name",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="running_on_fqdn",
            field=models.TextField(null=True),
        ),
        migrations.RunSQL(sql=forward, reverse_sql=backward),
        migrations.RemoveField(
            model_name="task",
            name="filesystem",
        ),
        migrations.RemoveField(
            model_name="task",
            name="running_on",
        ),
    ]
