# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 02:19
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chroma_core", "0032_forgetlustreclientjob")]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION api_key(
    IN _username text,
    OUT _key text
) AS
$func$
BEGIN
    SELECT ta.key
    INTO _key
    FROM auth_user as au
    INNER JOIN tastypie_apikey as ta on au.id = ta.user_id
    WHERE au.username = _username;
END
$func$ LANGUAGE plpgsql;
        """,
            reverse_sql="DROP FUNCTION IF EXISTS api_key(text);",
        )
    ]
