# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroma_core', '0032_devicehost_managedtargetmount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedtarget',
            name='volume',
        ),
        migrations.AlterField(
            model_name='managedtarget',
            name='bytes_per_inode',
            field=models.IntegerField(blank=True, help_text=b'Constant used during formatting to determine inode count by dividing the device size by ``bytes_per_inode``', null=True),
        ),
        migrations.AlterField(
            model_name='managedtarget',
            name='reformat',
            field=models.BooleanField(default=False, help_text=b'Only used during formatting, indicates that when formatting this target         any existing filesystem on the Device should be overwritten'),
        ),
    ]
