# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-23 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0033_remove_updatejob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurehostfencingjob",
            name="host",
        ),
        migrations.RemoveField(
            model_name="configurehostfencingjob",
            name="job_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="powercontroldevice",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="powercontroldevice",
            name="device_type",
        ),
        migrations.AlterUniqueTogether(
            name="powercontroldeviceoutlet",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="powercontroldeviceoutlet",
            name="device",
        ),
        migrations.RemoveField(
            model_name="powercontroldeviceoutlet",
            name="host",
        ),
        migrations.DeleteModel(
            name="PowerControlType",
        ),
        migrations.RemoveField(
            model_name="powercyclehostjob",
            name="host",
        ),
        migrations.RemoveField(
            model_name="powercyclehostjob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="poweroffhostjob",
            name="host",
        ),
        migrations.RemoveField(
            model_name="poweroffhostjob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="poweronhostjob",
            name="host",
        ),
        migrations.RemoveField(
            model_name="poweronhostjob",
            name="job_ptr",
        ),
        migrations.DeleteModel(
            name="IpmiBmcUnavailableAlert",
        ),
        migrations.DeleteModel(
            name="PowerControlDeviceUnavailableAlert",
        ),
        migrations.DeleteModel(
            name="ConfigureHostFencingJob",
        ),
        migrations.DeleteModel(
            name="PowerControlDevice",
        ),
        migrations.DeleteModel(
            name="PowerControlDeviceOutlet",
        ),
        migrations.DeleteModel(
            name="PowercycleHostJob",
        ),
        migrations.DeleteModel(
            name="PoweroffHostJob",
        ),
        migrations.DeleteModel(
            name="PoweronHostJob",
        ),
    ]
