# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-23 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chroma_core", "0034_remove_powercontrol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurecopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="configurecopytooljob",
            name="job_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="copytool",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="copytool",
            name="client_mount",
        ),
        migrations.RemoveField(
            model_name="copytool",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="copytool",
            name="filesystem",
        ),
        migrations.RemoveField(
            model_name="copytool",
            name="host",
        ),
        migrations.AlterUniqueTogether(
            name="copytooloperation",
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name="copytooloperation",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="forceremovecopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="forceremovecopytooljob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="removecopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="removecopytooljob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="removeunconfiguredcopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="removeunconfiguredcopytooljob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="startcopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="startcopytooljob",
            name="job_ptr",
        ),
        migrations.RemoveField(
            model_name="stopcopytooljob",
            name="copytool",
        ),
        migrations.RemoveField(
            model_name="stopcopytooljob",
            name="job_ptr",
        ),
        migrations.DeleteModel(
            name="ConfigureCopytoolJob",
        ),
        migrations.DeleteModel(
            name="Copytool",
        ),
        migrations.DeleteModel(
            name="CopytoolOperation",
        ),
        migrations.DeleteModel(
            name="ForceRemoveCopytoolJob",
        ),
        migrations.DeleteModel(
            name="RemoveCopytoolJob",
        ),
        migrations.DeleteModel(
            name="RemoveUnconfiguredCopytoolJob",
        ),
        migrations.DeleteModel(
            name="StartCopytoolJob",
        ),
        migrations.DeleteModel(
            name="StopCopytoolJob",
        ),
    ]
