jobs:
  # Check linting
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: azure-install-rust.yml
        parameters:
          rust_version: beta
      - script: |
          rustup component add clippy
        displayName: Install clippy
      - script: |
          cargo clippy --all-targets --all-features -- -W clippy::pedantic
        displayName: Check linting
        ${{ if parameters.crate }}:
          workingDirectory: $(Build.SourcesDirectory)/${{ parameters.crate }}
