#!/usr/bin/env python

import os
import sys
from chroma_core.lib.util import CommandLine, CommandError

virtualenv = os.environ.get('VIRTUAL_ENV', False)
if not virtualenv:
    sys.stderr.write("Don't run this outside of a virtualenv!\n")
    sys.exit(1)

try:
    import Crypto
except ImportError:
    sys.stderr.write("No Crypto module to patch!\n")
    sys.exit(1)

if virtualenv not in Crypto.__file__:
    sys.stderr.write("Crypto is not installed in virtualenv -- won't patch\n")
    sys.exit(1)

patch_file = os.path.join(os.path.abspath(os.path.dirname(__file__)),
                          "fix-dev-crypto.patch")
with open(patch_file) as f:
    patch_text = f.read()

os.chdir(os.path.dirname(Crypto.__file__))

try:
    CommandLine().try_shell(["patch", "-N", "-p1"], stdin_text = patch_text)
except CommandError, e:
    sys.stderr.write("Patch failed: %s\n" % e)
    sys.exit(1)

print "Successfully patched %s" % os.path.dirname(Crypto.__file__)
sys.exit(0)
